### ISSUE TITLE
checkered Texture blocking my view

### ISSUE THREAD

**Issue by Znuffles** [ValhelsiaTeam/Valhelsia#100]
spawned  in my Minecraft server and texture is blocking my screen

**Comment by Znuffles** [comment]
![image](https://user-images.githubusercontent.com/58963002/85241047-583d5380-b432-11ea-8078-9dfacd465a72.png)

**Comment by Vaelzan** [comment]
I believe this is a bug in OptiFine that happens with recent releases of it. Please disable OptiFine and let me know if this fixes the problem.

**Comment by Znuffles** [comment]
Fixed it I used the oldest pre-build of optifine 1.15
