### ISSUE TITLE
Block rendering issue in 2.2.3

### ISSUE THREAD

**Issue by AydenWasTaken** [ValhelsiaTeam/Valhelsia#103]
After updating to 2.2.3 the game is saying there is an error rendering a block and to check the logs. There are multiple blocks not getting rendered. Two of them are the refined storage disk drive, only when i put a third drive in, as well as refined pipes golden extractor not working. Log attached
[latest.log](https://github.com/ValhelsiaTeam/Valhelsia/files/4814675/latest.log)

**Comment by Vaelzan** [comment]
Please report this to the Refined Pipes issue tracker.

**Comment by AydenWasTaken** [comment]
Will do. Thanks.
