### ISSUE TITLE
using shaders and mining some blocks with a tool makes the screen turn black or white (depending on the shaders) for the duration of time you are mining the block.

### ISSUE THREAD

**Issue by justfeewee** [ValhelsiaTeam/Valhelsia#104]
Ive tried this with 5 different shaders as well as most of the tools (axes, pickaxes, shovels) basically any tool besides your fist to mine specific blocks. (pickaxes for stone, axes for wood)

**Comment by justfeewee** [comment]
when using axes most blocks turn the screen completely black when mining (the only block I've seen that doesn't are leaves

**Comment by Vaelzan** [comment]
This is a bug in the most recent releases of OptiFine. See here: https://github.com/sp614x/optifine/issues/4088

**Comment by justfeewee** [comment]
> This is a bug in the most recent releases of OptiFine. See here: [sp614x/optifine#4088](https://github.com/sp614x/optifine/issues/4088)

oh I see, thank you for the quick reply!
