### ISSUE TITLE
Copper Ingot conversions in 2.2.3

### ISSUE THREAD

**Issue by mbainter** [ValhelsiaTeam/Valhelsia#106]
Just updated to 2.2.3 from 2.2.1a and discovered something a bit off around at least Copper ores.  

Take 9 copper ores from a non-immersive-engineering mod (mekanism, Create, etc) and make a block and it'll create an Immersive Engineering copper block -- but it's corrugated and green.  Weird.  It's also what shows up in the JEI.

Put this in a crafting table and you can get ingots back -- so minecraft thinks it's a copper block.

Put it in a compacting storage drawer and...you can just get the block back.  It doesn't know what to do with it.

Put ingots from Create, Mekanism or Immersive engineering in a compacting storage drawer and they all create appropriate copper blocks -- even the one for Immersive engineering looks right (i.e. not green).  Take them out, put them in, that works fine.

**Comment by Sabster** [comment]
Can this get fixed ASAP - it's now crashing my server (with the 3 different coppers and converting them)
