### ISSUE TITLE
Just installed this instance but can't get it to start

### ISSUE THREAD

**Issue by JRSofty** [ValhelsiaTeam/Valhelsia#110]
I've attached the log with the error. This could very well be caused by Twitch, but I can't be for certain.

[latest.log](https://github.com/ValhelsiaTeam/Valhelsia/files/4838531/latest.log)

**Comment by baldheadlilgirl** [comment]
same problem here also.

**Comment by Vaelzan** [comment]
Please see the readme here: https://github.com/ValhelsiaTeam/Valhelsia/issues/5

We handle all support via Discord. In this case, it's a Twitch bug that doesn't install Forge if the installation path has a space anywhere in it. It's detailed in the #faq channel on Discord: https://discordapp.com/invite/reQZEXu
