### ISSUE TITLE
Server Crash after breaking Advanced Compressor Factory

### ISSUE THREAD

**Issue by tplc10** [ValhelsiaTeam/Valhelsia#112]
[message.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4841386/message.txt)

**Comment by Vaelzan** [comment]
Please report this to Mekanism, They should be able to fix it fairly easily.

**Comment by Khytwel** [comment]
No more support for Mekanism in 1.15. Not reproducible in 1.16, the bug is maybe fixed.

https://github.com/mekanism/Mekanism/issues/6255
