### ISSUE TITLE
Suggestion: Add ServerTabInfo

### ISSUE THREAD

**Issue by Crimix** [ValhelsiaTeam/Valhelsia#113]
I think [ServerTabInfo](https://www.curseforge.com/minecraft/mc-mods/server-tab-info) could be beneficial, especially if more dimension are added.
It is a simple mod to see the tps of all loaded dimensions in a nice UI overview.

**Comment by Vaelzan** [comment]
One step ahead of you... https://imgur.com/mqVazFw

:)

**Comment by Crimix** [comment]
Nice :+1:
