### ISSUE TITLE
Startup Crash on 2.2.3

### ISSUE THREAD

**Issue by kvsikand** [ValhelsiaTeam/Valhelsia#115]
Hi, wanted to give this modpack a try but am getting an error during initialization that causes MC to crash while loading hte main menu.

I'm using MultiMC to load the zip file as an "instance", and launching from there.

Here is the log on startup; to me it looks like doggytalents is freaking out trying to register colors? but I'm not exactly sure how to "fix" this

[mc.log](https://github.com/ValhelsiaTeam/Valhelsia/files/4848600/mc.log)

**Comment by Vaelzan** [comment]
1) Please use Discord for support in future.

2) The Fancy Menu mod doesn't work in Linux. We're removing it in favour of a better mod next update, but for now please remove it manually (it will just revert to the default menus, which work just fine).

3) Doggy Talents is never actually the issue, it's a bug in Forge that reports that as the culprit.
