### ISSUE TITLE
Crashes when clicking play

### ISSUE THREAD

**Issue by artificialblac** [ValhelsiaTeam/Valhelsia#122]
Hey I'm in need of help playing this modpack, I have been trying to change the minecraft launcher to 1.6.93, but somehow every time I press play it crashes automatically sending me a message saying

![Screen Shot 2020-07-02 at 11 50 09 PM](https://user-images.githubusercontent.com/67741541/86355496-da453c00-bcbe-11ea-8b9d-220782b58e04.png)

I want to know what is wrong and if there's a way to fix it, because I took the whole day trying to set this game up, before I had a problem freezing before I could press play I think it's because I was using an old launcher but now that I am using a new one it comes up with that problem, hopefully someone can help because I've been wanting to play this game already.

**Comment by Vaelzan** [comment]
Twitch isn't compatible with newer mod packs (1.14 / 1.15) on Mac OS X. Please use either GDLauncher or MultiMC.

Also, in future please use Discord for support. You'll get much faster help there.
