### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by deathgub** [ValhelsiaTeam/Valhelsia#125]
Hi, I recently downloaded your modpack as I saw it on Curse, but when I try to launch it the game keeps crashing, I opened the logs and it said "Failed to find Minecraft resource version 1.15.2-20200515.085601" I tried downloading forge 1.15.2 as well as regular version of the game and nothing seems to work. I would appreciate it if I could get your assistance with this issue.

Thanks for the help

**Comment by Vaelzan** [comment]
Please use Discord for support in the future, it's usually faster as more people are able to help there. See the readme: https://github.com/ValhelsiaTeam/Valhelsia/issues/5

The crash you have there is the first entry in our FAQ on Discord, but you can also try something like GDLauncher or MultiMC which normally work better as they handle installing Forge correctly, while Twitch often does not.
