### ISSUE TITLE
Server is timing out players while attempting to connect, takes 3+ attempts before allowing them to connect.

### ISSUE THREAD

**Issue by Charles1nCharge** [ValhelsiaTeam/Valhelsia#127]
Howdy folks, I'm hoping y'all can help me out with a little problem I'm having. I have a premium server with BisectHosting and I am running the latest version of the Valhelsia server (2.2.3). I used the autoinstaller to put all the files together and it seems to be running fine, however when one of my friends tries to connect to the server it will time them out a couple times before they can fully load into the game. When checking the console I am getting this:

03.07 12:42:00 [Server] Server thread/INFO <PLAYER> joined the game
03.07 12:42:00 [Server] Netty Epoll Server IO #35/ERROR Could not serialize net.minecraftforge.server.command.ModIdArgument@702bb971 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
03.07 12:42:00 [Server] Netty Epoll Server IO #35/ERROR Could not serialize net.minecraftforge.server.command.ModIdArgument@6e1a74d6 (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
03.07 12:42:00 [Server] Netty Epoll Server IO #35/ERROR Could not serialize net.minecraftforge.server.command.EnumArgument@2850b069 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
03.07 12:42:00 [Server] Netty Epoll Server IO #35/ERROR Could not serialize net.minecraftforge.server.command.EnumArgument@7e3966ee (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
03.07 12:42:00 [Server] Netty Epoll Server IO #35/ERROR Could not serialize com.ldtteam.structurize.commands.arguments.MultipleStringArgument@20a1db5 (class com.ldtteam.structurize.commands.arguments.MultipleStringArgument) - will not be sent to client!
03.07 12:43:00 [Disconnect] User <PLAYER> has disconnected, reason: Timed out
03.07 12:43:00 [Server] Server thread/INFO <PLAYER> left the game

Another issue that we are seeing is that when we have a server added in the multiplayer tab, we are seeing an "Incompatible FML modded server" error. [Link](https://imgur.com/a/aiFgHlI)
I made sure that all of us are running the latest version of the modpack, and I have even reinstalled the server pack and it is giving me the same issue. If any of y'all can help me out with this I would greatly appreciate it.

**Comment by UberAffe** [comment]
It's best to ask these things on the discord server but you can probably fix it be updating the random patches mod and increasing the timeout value in the config.

**Comment by BurritoB0b** [comment]
its minecolonies, i have no idea what part so i had to disable it completely. first login actually works. hope this helps sorry i cant figure out which file.

**Comment by Bulluk** [comment]
I grabbed the server world, loaded it into singleplayer. Loaded and played just fine.

Copied it again back to the server, works smoothly now.

**Comment by DrRuhe** [comment]
Since the Fixed for next release tag is here, is there a verified workaround until the next version releases? We have this exact problem on our server and it's driving us insane.

**Comment by Khytwel** [comment]
Normally fixed in the latest version 2.2.5a. Reopen the issue if not.

**Comment by Khytwel** [comment]
For the "Incompatible FML modded server" error, is not our part. It is up to the developers of the mods concerned to fix this bug. This will be done for Valhelsia 3, but for Valhelsia 2 the number of mods to be checked is far too large for us.
