### ISSUE TITLE
Shader's causing visual screen glitch

### ISSUE THREAD

**Issue by TheJuneGemini** [ValhelsiaTeam/Valhelsia#129]
I'm not sure why, but every time I try using Shaders (I've tried around 5 different packs) my screen starts glitching whenever I try and break a block. For example when I am using BSL shaders my screen turns completely light purple whenever I try and break a block, another example is when I use SUES Renewed Shaders my screen turns completely black whenever I try and break a block. Its fine whenever I turn off Shaders, as there are no problems then, but when they are turned on it keeps glitching out. Please help!

**Comment by TheJuneGemini** [comment]
Answer was found on Valhelsia Discord

**Comment by domsch1988** [comment]
Would you mind posting the solution here? I'm running into the same issue.

**Comment by TheJuneGemini** [comment]
Yea Sure! 
If you're having an issue when breaking blocks while shaders are on, the cause is that there is a bug in recent previews of OptiFine. You can use OptiFine pre23 to get around that, and it can be downloaded from here: https://github.com/sp614x/optifine/files/4808411/preview_OptiFine_1.15.2_HD_U_G1_pre23.jar.zip - to install it, extract the .jar file from the zip and move it into your mods folder.
