### ISSUE TITLE
Minecraft maps can cause a crash in some situations.

### ISSUE THREAD

**Issue by Loupning** [ValhelsiaTeam/Valhelsia#13]
So when I mapped a Rosewood Mountain I crashed with a Player Tick problem. I had to edit my NBT data to delete the map from my inventory to be able to load to my world again.

**Comment by Vaelzan** [comment]
This isn't limited to just the Rosewood Mountain so I have updated the title to reflect that. It also happens occasionally with treasure maps. If anybody knows what causes this please provide more information. I haven't found a consistent cause as some maps work fine and others don't.

**Comment by olabgaming** [comment]
Every time this has occurred for me, it was in previously generated chunks in older versions of the pack. New areas did not cause the error. If it is directly tied to old chunk generation (probably specifically loot chests), there may not be a fix other that to delete chunks in an editor and start fresh where possible.

**Comment by djeezuss** [comment]
I think I have the same issue, here's the crash log:
[crash-2020-05-17_17.01.33-server.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4641036/crash-2020-05-17_17.01.33-server.txt)
I'm on the version **2.2.0a** of the modpack.

**Comment by Vaelzan** [comment]
@djeezuss Was your world created in that version of the pack, or did you update from an older version?
