### ISSUE TITLE
Bonsai Trees Conflict

### ISSUE THREAD

**Issue by Areorah** [ValhelsiaTeam/Valhelsia#131]
![image](https://user-images.githubusercontent.com/19559232/86518350-ee8c5480-bdf6-11ea-9918-8aab0ac53e12.png)

I can't pick which outcome I want, so I'm stuck with the top one, getting the leaves & normal sticks, rather than the netherwood sticks & bananas. A possible fix could just be to remove the normal sticks and add the banana, rather than having two separate recipes.

**Comment by Vaelzan** [comment]
This happened because we added our own recipe for Netherwood Saplings before Bonsai Trees added official support. We'll be removing our recipe for the next update of the pack, as there aren't meant to be duplicate recipes at all - they just added theirs in the most recent update.

**Comment by Khytwel** [comment]
Fixed in the latest update (2.2.4), thanks you for your report!
