### ISSUE TITLE
[Velhelsia 2] Game Crashing While Starting Up

### ISSUE THREAD

**Issue by SquidKidd** [ValhelsiaTeam/Valhelsia#133]
Hello there! I don't know the proper lines for posting crash reports, or who I need to talk to in order to get help, but this is the best I have. The modpack crashes while starting up using MultiMC. I have tried my best to figure out what is crashing the game, but I'm not proficient enough with Forge ModLoader in order to diagnose it. I cannot use Twitch Launcher (see below).

System Specs:
i7-3770k @ 3.9GHz
AMD ATI Radeon R9 290
16GB of RAM
Linux Mint 20 Cinnamon x86_64
Kernal Version 5.4.0-40-generic

Crash Report: https://paste.ee/p/OdHLD

**Comment by Vaelzan** [comment]
Please remove the Fancy Menu mod from the mods folder. It doesn't work on Linux. We're removing the mod from the pack entirely in the next update.

Also, please use Discord for support in the future. You'll get a faster response there.

**Comment by SquidKidd** [comment]
Thank you for the help, and I will keep in mind I need to go to Discord instead. After removing Fancy Menu (and CraftPresence) the error changed to Doggytalents. I will likely follow this up on Discord!
