### ISSUE TITLE
Disconnecting after connection Lan World

### ISSUE THREAD

**Issue by ReptarKing0Zone** [ValhelsiaTeam/Valhelsia#134]
Hello there,

I am trying to play with my wife with a LAN connection. Everything has been working fine until now she is getting disconnected after 30 seconds with the following error message: internal exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException

**Comment by Vaelzan** [comment]
If you were using Open to LAN rather than a dedicated server, that isn't supported. The majority of mod developers don't ever even try their mods in that way. You'll need to run the server pack instead.
