### ISSUE TITLE
Game crashes as soon as its launched

### ISSUE THREAD

**Issue by AydenWasTaken** [ValhelsiaTeam/Valhelsia#137]
As soon as i click play on the minecraft launcher, the game loads for about half a second and crashes back to the launcher. No crash reports, and no info in the crash message (other than the generic "An error occured" message). Happening on 2.2.4 and after a clean install

**Comment by Khytwel** [comment]
Can you send the latest logs?

**Comment by AydenWasTaken** [comment]
@Khytwel this seems to happen with more 1.15 packs, but not with packs on older versions. Could my mc installation for 1.15 get corrupted for some reason? Valhelsia 2 ran fine before this update, but now multiple packs on 1.15 don't work anymore. This does not seem to be a valhelsia problem though

**Comment by Khytwel** [comment]
![image](https://user-images.githubusercontent.com/54046029/86631973-17674200-bfcf-11ea-852a-bf865d879be3.png)
Please come directly to our Discord server for this kind of problem.
https://discord.com/invite/reQZEXu
