### ISSUE TITLE
Errors in the ServerStart.sh file.

### ISSUE THREAD

**Issue by Banaando** [ValhelsiaTeam/Valhelsia#138]
With the ServerStart.sh file there are 2 errors which are a missing space and an extra period.

At the end of the ServerStart.sh file there is this: AlwaysPreTouchforge-.1.15.2-31.2.30.jar nogui
     There is an extra dot before the 1.15.2 that shouldn't be there because that's not the name of the jar file.
     There should also be a space after the AlwaysPreTouch.

Corrected it would look like this: AlwaysPreTouch forge-1.15.2-31.2.30.jar nogui

**Comment by Miwoj01** [comment]
Yeah, after this you are able to start server? Because i get an error and server shut down

**Comment by Banaando** [comment]
Yeah, I'm able to start the server after I correct this and accept the eula.

**Comment by Khytwel** [comment]
Yes it's an error I forgot to fix on the new serverstart. This will be done for the next version.

**Comment by Khytwel** [comment]
Fixed in the latest version 2.2.5a.
