### ISSUE TITLE
Silent Gear Tools unable to be repaired

### ISSUE THREAD

**Issue by Drackion** [ValhelsiaTeam/Valhelsia#140]
After i updated my pack to the latest version i created a new world (did't get far in old world and minecraft stone was impossible to find so i created a new world "Terraforged terrain generation") and i noticed that i wasn't able to repair my silent gear tools.

**Comment by Vaelzan** [comment]
The latest Silent Gear update changes the way tools are repaired. You need a repair kit now. This is intentional but the CurseForge page for Silent Gear hasn't been updated to explain it yet.

**Comment by Drackion** [comment]
Ok thank you for the information

**Comment by Speedyrv** [comment]
This makes the pack unplayable.
