### ISSUE TITLE
SilentGear tools don't repair in crafting grid (2.2.4)

### ISSUE THREAD

**Issue by manfredschroeder** [ValhelsiaTeam/Valhelsia#141]
Trying to repair silent gear tools with their respective materials in a grafting grid doesn't work after upgrading world to 2.2.4. Broken or worn tools can only be repaired in an anvil by expending XP like vanilla tools.

**Comment by Vaelzan** [comment]
This is an intentional change in Silent Gear. You can use Repair Kits now.

**Comment by Speedyrv** [comment]
Then the starter pack needs to be edited to include a dagger so you can create a repair kit. This changes makes the starter tool pack useless. Well other than having chest full of un-repairable items.

**Comment by Vaelzan** [comment]
You can create a dagger without a blueprint. See here: https://github.com/SilentChaos512/Silent-Gear/issues/160
