### ISSUE TITLE
Launcher won't load

### ISSUE THREAD

**Issue by LiterallyAqua** [ValhelsiaTeam/Valhelsia#142]
As I'm trying to get into the mod pack straight from twitch by clicking play, the main launcher has been loading for the past hour and seems like it will not ever load. Please help !

<img width="907" alt="Screen Shot 2020-07-07 at 12 23 07 PM" src="https://user-images.githubusercontent.com/67970664/86812514-1aa11300-c04d-11ea-834f-500c60a7143b.png">

**Comment by Khytwel** [comment]
For this kind of problem please come directly to our discord server.
https://discord.com/invite/reQZEXu
