### ISSUE TITLE
Game crashes when placing two vertical slabs on top of each other

### ISSUE THREAD

**Issue by coiledmocha** [ValhelsiaTeam/Valhelsia#145]
Game crashed a few times now after I tried to place two vertical gray colored plank slabs on top of each other. 
Screen freezes, jumps to "Saving World" screen and then closes. No additional mods were used and it happened on the newest version as of 07/08/2020.

Edit: Seems to have only happened in one specific spot. I don't know if crash reports may help in this case, but I'll upload them anyway:

[crash-2020-07-08_15.07.10-client.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4902394/crash-2020-07-08_15.07.10-client.txt)

**Comment by Vaelzan** [comment]
I believe the update to DoubleSlabs that we're including in the next pack update will fix this.

**Comment by Khytwel** [comment]
Normally fixed in the latest version 2.2.5a.
