### ISSUE TITLE
my world won’t open

### ISSUE THREAD

**Issue by altminecraft** [ValhelsiaTeam/Valhelsia#148]
when I click to play in my world, it stops responding, and in the first time I played everything was alright

**Comment by Sabster** [comment]
I can tell you no one will be able to help without some sort of log...

**Comment by Vaelzan** [comment]
Please read the readme before posting issues: https://github.com/ValhelsiaTeam/Valhelsia/issues/5

We handle support via Discord here: https://discordapp.com/invite/reQZEXu
