### ISSUE TITLE
Crafting Crashing the Game

### ISSUE THREAD

**Issue by MaybeEmma** [ValhelsiaTeam/Valhelsia#149]
So far I have encountered issues crafting Iron Tool Rods and Steel Blocks using the shift-right click mechanic to craft multiple at the same time. When doing so the game immediately freezes and crashes. Crafting the items one at a time works, but unfortunate for those who stumble across it by accident like I did. ( Using a Storage Request Table, didn't test with a regular or other modded crafting tables.

[crash-2020-07-08_23.22.11-server.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4894662/crash-2020-07-08_23.22.11-server.txt)
 )

**Comment by Vaelzan** [comment]
I believe that you've run into this bug here: https://github.com/TheIllusiveC4/Polymorph/issues/11

in which case we will include a fix in the pack once one is available.

**Comment by GsakuL** [comment]
hi, just came across this now. The mod is currently already v0.6 on curse forge (yesterday)

**Comment by Vaelzan** [comment]
It's one of the mods being updated in the next pack update, which should be out reasonably soon.

**Comment by Khytwel** [comment]
Fixed in the latest version 2.2.5a.
