### ISSUE TITLE
Botany Pots "soil" listed as a iron clay bar - Valhelsia 2

### ISSUE THREAD

**Issue by DrakonSK** [ValhelsiaTeam/Valhelsia#151]
Just as the title says, when looking at the type of soil you can use for botania flowers, you can see a iron ingot labeled as "clay" with a growth modifier of an insane amount.
![2020-07-09_09 17 50](https://user-images.githubusercontent.com/67998134/87051724-93c37600-c1c5-11ea-8f3c-2341defcdb33.png)

**Comment by Vaelzan** [comment]
I've reported it to the Botany Pots developer. pretty sure they were using it to test a new feature and forgot to remove it. https://github.com/Darkhax-Minecraft/BotanyPots/issues/53

**Comment by Darkhax** [comment]
Yep, this is a debug recipe and has now been removed. Thanks for reporting it. 

https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/3000981

**Comment by Vaelzan** [comment]
@Darkhax Really appreciate the quick fix. :)

**Comment by Khytwel** [comment]
Fixed in the latest version 2.2.5a.
