### ISSUE TITLE
Druidcraft: Mud

### ISSUE THREAD

**Issue by FirstBitStudios** [ValhelsiaTeam/Valhelsia#152]
I am unable to create Mud after attempting to for some time, looks like issue is due to overlapping recipe with rocky soil.

**Comment by DrakonSK** [comment]
You need to craft it in watee

**Comment by FirstBitStudios** [comment]
I am, I have stood in water an put it down, put it down in water when not in water myself, sottd in water and put it down not in water, like trust ive tried all possible scenarios. It just never happened, myself and 2 other players on my server all have attempted this but no results

**Comment by Vaelzan** [comment]
Do you have the Polymorph button show up above the output? You can click it to change output from Rocky Dirt to Wet Mud Bricks.

**Comment by FirstBitStudios** [comment]
yea, turns out my friends and I are all blind and stupid, that was it, thank you
