### ISSUE TITLE
Unable to Obtain Immersive Engineering Hemp

### ISSUE THREAD

**Issue by BlackWingReg** [ValhelsiaTeam/Valhelsia#153]
In the most recent update of the pack, I am unable to obtain immersive engineering hemp seeds from breaking grass, and there doesn't seem to be any other way to obtain them. It feels like they've been replaced by the Hemp Seeds from Druidcraft, which don't produce equivalent items or cross connect. This makes it impossible to create upgraded windmills, balloons and jump cushions.

I'm unaware of alternate methods to obtain these seeds.

**Comment by Vaelzan** [comment]
Waiting for an IE update: https://github.com/BluSunrize/ImmersiveEngineering/issues/4046
