### ISSUE TITLE
Can't create I/E Iron Mechanical Component

### ISSUE THREAD

**Issue by mastrude** [ValhelsiaTeam/Valhelsia#154]
[https://imgur.com/8IOwC38](url) Producing iron plates in the stamper gives you plates from Create. Copper ingots are from Silent's.  In the Engr Workbench, the bench shows iron mech components but you can't click to create them. [Valhelsia 2 2.2.4] Workaround is to make them in Silent's crafting table.

**Comment by Vaelzan** [comment]
Waiting on an IE update to resolve this: https://github.com/BluSunrize/ImmersiveEngineering/issues/3988

I believe issue is the order of blueprint items not always being the same: 
https://i.gyazo.com/c4a7f8245159964250d84779e227ae6b.png
https://i.gyazo.com/48d9347b11db8afeacd741f4805e85f1.png

Which means that if you get lucky and can get the order to work, then you can craft them currently.  Break the workbench and replace it until it works as a workaround.
