### ISSUE TITLE
when i throw the botanica book through the portal nothing comes back

### ISSUE THREAD

**Issue by thetechy2** [ValhelsiaTeam/Valhelsia#155]
i just wanna continue the mod pls

**Comment by Vaelzan** [comment]
This has been reported on the Botania issue tracker and we will update the pack when they fix it. https://github.com/Vazkii/Botania/issues/3311

**Comment by thetechy2** [comment]
f this is my first time doing botanica and my world has cheats disabled. guess i gotta download a save editor
