### ISSUE TITLE
Multiple Gravestone like mods colliding

### ISSUE THREAD

**Issue by KingOfMangonia** [ValhelsiaTeam/Valhelsia#156]
In the modpack, there is hardcore revival, corpses and quark oddities.

Hardcore revival should let you be revived but doesn't trigger and the totem of holding from quark oddities completely negates the corpses mod and has on multiple occasions caused me much grief.

There doesn't seem to be a reason for having all three of these mods when two of these don't even work. 

Playing on version 2.2.4

**Comment by Khytwel** [comment]
You modpack must be very badly installed to still have the Hardcore Revival and Corpse mods that were removed a few versions ago. Make a new installation with the GDLauncher.

https://gdevs.io/
