### ISSUE TITLE
[Mod Suggestion] RFTools Dimensions

### ISSUE THREAD

**Issue by DannyParker0001** [ValhelsiaTeam/Valhelsia#161]
I find it weird that you have all the other RFTools modules but the most fun one: RFTools Dimensions.
If you didnt know, it lets you create your own dimensions using dimlets (You can make a vanilla enderman farm to get these), then you can do whatever you want with the generation, I often use it to get an always day desert dimension for brine generation in Mekanism.
You can do much more than this though, really cool & interesting mod.

**Comment by Vaelzan** [comment]
RFTools Dimensions isn't out for Minecraft 1.15 or 1.16 so it is impossible to add it to the pack.

**Comment by LittleCircles** [comment]
https://www.curseforge.com/members/mcjty/projects - Look at the latest ones

**Comment by DannyParker0001** [comment]
Oh shit ye, my bad. I really miss it :( Looks like he does plan on eventually updating it though.
