### ISSUE TITLE
Recipe conflict: Steel fence (Immersive engineering/Mapper's base

### ISSUE THREAD

**Issue by Bulluk** [ValhelsiaTeam/Valhelsia#162]
You can't craft the Immersive Engineering steel fences. Instead you can only craft the Mapper's Base Steel Fences. Which you cannot use in the Immersive Engineering multiblocks. Therefor you cannot complete some of the Immersive Engineering multiblocks such as the Crusher

**Comment by Vaelzan** [comment]
Click the button above the crafting output to change which items gets created.

**Comment by Bulluk** [comment]
Okay, this only displays in the normal Crafting Table. Not in any other modded Crafting Table.
For example the Refined Storage Crafting Grid. Or just the Engineer's Crafting Table from Immersive Engineering
