### ISSUE TITLE
Cant use any shader

### ISSUE THREAD

**Issue by Rocksonix** [ValhelsiaTeam/Valhelsia#164]
Hi Valhelsia Team and thanks for this awesome Modpack.
We have a bit of a problem to apply a shader to this Modpack.,
This is what ive done so far:

I installed optifine; I put the following optifine version into the mods folder "preview_OptiFine_1.15.2_HD_U_G1_pre30"
Then i choosed Sildurs Shader.
The shader is working quite fine BUT as soon as I want to destroy any block ingame with any kind of tool, I get a blackscreen ( or some weird graphic bugs ) as long as I klick on this block.
I can destroy any block without any tools and have no problems with it.
this is so weird.
My girlfriend has the same problems.
Maybe i am missing something here.

I tried every known Shader like Sildurs, SEUS, KUDA, BBVanillaReborn ...

Maybe you guys could help us this fix this. Thanks !!

**Comment by Vaelzan** [comment]
Please look at the pinned post of the support channel of our Discord server. It's a bug in OptiFine that has a fix there.
