### ISSUE TITLE
Frezze when loading world.

### ISSUE THREAD

**Issue by CalualaMic** [ValhelsiaTeam/Valhelsia#167]
My game is frezing when loading a world and i use 4 gb RAM on the game.

**Comment by Khytwel** [comment]
You would have read the whole page that presents our modpack, you would have noticed that the modpack does not work with 4GB and that you need a minimum of 5GB of RAM. Moreover, our GitHub is not intended to fix this kind of problem. Go to our Discord server for this kind of thing.
![image](https://user-images.githubusercontent.com/54046029/87848940-0ed30d80-c8e5-11ea-9438-4efb4c61e24c.png)
