### ISSUE TITLE
Atum 2 Problems

### ISSUE THREAD

**Issue by LittleCircles** [ValhelsiaTeam/Valhelsia#170]
I made a Atum 2 portal in my server, something happened and when I tried to rejoin I got the error "Internal Server Error". I had to edit my players NBT Data to fix my player to let my self into my server. I then tried in a SP world and it crashed my game on joining the Atum 2 Dim.

**Comment by ZarikTH** [comment]
having similar problems here.

**Comment by xepps** [comment]
Similar issues for me.

I created a new 2.2.5 test world and created the portal to atum successfully.

As I entered the portal, I got the achievement for going to midnight, and for going to atum, but remained in the overworld.

Potential dimension id mismatch?
![image](https://user-images.githubusercontent.com/1401667/87808107-18ab3100-c851-11ea-8b41-87f99f86f453.png)

**Comment by Khytwel** [comment]
Can you send the latest log?

**Comment by Khytwel** [comment]
Normally fixed in the latest version 2.2.5a. Reopen the issue if not.
