### ISSUE TITLE
Crash while in the Nether

### ISSUE THREAD

**Issue by xshooperx** [ValhelsiaTeam/Valhelsia#171]
Game is crashing randomly while running around in the Nether. Wasnt happening before the update 

[crash-2020-07-17_19.41.17-server.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4939422/crash-2020-07-17_19.41.17-server.txt)
[crash-2020-07-17_20.00.36-server.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4939423/crash-2020-07-17_20.00.36-server.txt)

**Comment by TheLegendWeeb** [comment]
I get a similar crash when entering the nether

**Comment by TheLegendWeeb** [comment]
some people on the discord are having the same issue also

**Comment by xshooperx** [comment]
Must have something to do with one of those 3 mods: mystical world, fairylights, atum 2

I removed those 3 for testing and it seems to work now.

**Comment by TheLegendWeeb** [comment]
i tried without atum 2 and the issue persists

**Comment by TheLegendWeeb** [comment]
it doesn't crash when mystic world is removed

**Comment by xshooperx** [comment]
Okay, so its that mod, good to know.

**Comment by Joesudoedapizza** [comment]
I have also gotten this crash with my crash log here
[crash-2020-07-17_21.49.41-server.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4940489/crash-2020-07-17_21.49.41-server.txt)
Can confirm that removing mysticalworld-1.15.2-2.0.1 resolves the issue

**Comment by Khytwel** [comment]
Fixed in the latest version 2.2.5a.
