### ISSUE TITLE
Coke Oven & Blast Furnace Not Working - Immersive Engineering

### ISSUE THREAD

**Issue by somebodypoop** [ValhelsiaTeam/Valhelsia#172]
Upon attempting to get a coke oven to work, nothing happens and the item sits there and drops on the floor when exiting its GUI. Same thing happened for my buddy who tried to use a blast furnace. This makes me think a lot of other stuff isn't going to work in this Valhelsia update, so I'm holding off on playing for now.

**Comment by Yahkub-R** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/4073
