### ISSUE TITLE
[2.2.5a] Atum mobs crashing server

### ISSUE THREAD

**Issue by Stifling-Bossness** [ValhelsiaTeam/Valhelsia#178]
After instituting the client-side fixes in #176 , players on our server were able to explore Atum without getting stuck in crash loops. Shortly afterwards, however, we begun to get server crashes seemingly caused by Atum mobs. 

[Latest](https://gist.github.com/Stifling-Bossness/4ee17e594b673816ab277d6967d109d6)
[Debug](https://gist.github.com/Stifling-Bossness/fe7ccdb241b8e7ca560960cbc4ee60f9)

We're unsure exactly what situation is causing this as it's impossible to stay on long enough to troubleshoot, apologies for that.
We'll be rolling back to 2.2.4 for a while as we let 2.2.5 stabilize.

**Comment by ValhelsiaTeam** [comment]
The problem is normally fixed since version 2.2.6. Re-open a way out if the problem is still present.
