### ISSUE TITLE
Better Animals Plus mod request

### ISSUE THREAD

**Issue by Rasmend** [ValhelsiaTeam/Valhelsia#180]
Just a request to add the mod Better Animals Plus to the pack. It helps fill out the world with new, but real (with a couple of exceptions), creatures in excellent detail. I currently run a private server for a few friends. One of the complaints was the world felt a little empty. The mod also adds ways of decorating using the animals from the mod. 

p.s. noted that no seeds from Simple Farming were spawning. Did not know if this was intentional or a known problem.

**Comment by ZarikTH** [comment]
on the note of simple farming, those are coming next simple farming update. its a bug thats already noted! :) (also, good idea for better animals)
