### ISSUE TITLE
Crash after laying a slab #2.2.4 

### ISSUE THREAD

**Issue by thomaschambellan** [ValhelsiaTeam/Valhelsia#182]
When I want to put a tile in a place (always the same) my games crash but not the server.
this happens in several places.
   ###[crash-2020-07-19_10.46.45-client.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4943459/crash-2020-07-19_10.46.45-client.txt)

**Comment by Vaelzan** [comment]
Please don't report issues for older versions. This issue should be fixed in the updated pack.
