### ISSUE TITLE
Connection Closed - mismatched mod channel list

### ISSUE THREAD

**Issue by Rasmend** [ValhelsiaTeam/Valhelsia#189]
Hello! For background, I am the server owner and admin. Here's what is happening from the beginning:

- Loading the latest server files from CurseForge onto a server provided by Shockbyte that uses Multicraft. 4gbs of RAM.
- Using the Forge Launcher provided in the modpack to launch the server
- Server launches just fine. World is created. We all play it for a little while.
- Server crashes for whatever reason or simply restarts. The reason isn't generally important.
- We all get the error message, "Connection closed- mismatched mod channel list" when trying to rejoin
- We were all just playing on the server so the mods for it couldn't possibly have changed.
- The console says that the server is up and running just fine. No crashes, no problems, but for some reason we can't join because our "Mod channel list" is mismatched. 
- This has happened several times and results in me making a new world and restarting the server with a new world only to have the same problem again.

I post the problem here because I ran another modpack on the same server before and never had this issue. We played that modpack for a week and never ran into the issue.

**Comment by ValhelsiaTeam** [comment]
This problem should be fixed since version 2.2.6 for Valhelsia 2.
