### ISSUE TITLE
crash at startup 

### ISSUE THREAD

**Issue by BigbagelBoy** [ValhelsiaTeam/Valhelsia#193]
hi I have problems with startup im using the twitch launcher and forge 31.2.31 and i cant start the game without crashing it does anyone know what im doing wrong?

**Comment by Vaelzan** [comment]
Please use Discord for support on future. Twitch has a bug where it won't install Forge if you have a space in the installation path anywhere. Use GDLauncher or MultiMC instead or follow the steps in the FAQ on Discord if you want to contribute with Twitch.
