### ISSUE TITLE
Upgraded to Valhesia 3.0.7 and biomes got mixed

### ISSUE THREAD

**Issue by Rice-SD** [ValhelsiaTeam/Valhelsia#197]
I host my own Ubuntu server and am running pure Valhesia, started the server once Valhesia 3 started. Minecraft was fine until I upgraded to 3.0.7 today and found that the Forest we were building in was now classified as a Tundra (no snow, no change to the physical biome, just is seen as a Tundra). It's almost like some change from 3.0.6 > 3.0.7 changed the Biome mapping or something? 

Thanks

**Comment by Khytwel** [comment]
Unfortunately BOP is still in BETA version so it can happen....
![image](https://user-images.githubusercontent.com/54046029/88430088-26842780-cdf8-11ea-8295-98976baa2e41.png)
