### ISSUE TITLE
 Low fps

### ISSUE THREAD

**Issue by helhel1** [ValhelsiaTeam/Valhelsia#198]
Hello, my FPS does not rise above 5, with the minimum graphics settings. What could be the problem? Allocated 8 GB RAM, i7 960 3.8 GHz, r9 270x

**Comment by NineteenLettersOnly** [comment]
Do you have optifine "smooth FPS" enabled? (it sometimes causes a decrease)

**Comment by Khytwel** [comment]
To play large modpacks you need a good computer, try Valhelsia: Origins.
