### ISSUE TITLE
Missing support for a lot of saplings in bonsai hoppers

### ISSUE THREAD

**Issue by dskw** [ValhelsiaTeam/Valhelsia#20]
Hi,

a lot of trees are missing support for the bonsai hoppers.
A small list of mods I had tried:
Misc Additions, Autumnity, Fruit Trees, Swamp Expansion

**Comment by Khytwel** [comment]
We'll see what we can do.

**Comment by Khytwel** [comment]
Implemented in the version 2.2.0 of Valhelsia 2 :)
