### ISSUE TITLE
Mekanism and Silent's Mechanisms providing same ores

### ISSUE THREAD

**Issue by dskw** [ValhelsiaTeam/Valhelsia#21]
Just a minor thing:

Mekanism and Silent's Mechanisms both provide Tin and Copper ores for world gen.
The resulting ingots should be compatible, so maybe one of the types could be disabled safely

**Comment by Vaelzan** [comment]
Once we are certain that either ore + ingot will work for any recipe or machine we will consider this. At the moment there is still the occasional compatibility issue that pops up, but it looks like we've fixed most of them now.

**Comment by Khytwel** [comment]
Implemented to 2.2.2.
