### ISSUE TITLE
[Suggestion] Add Applied Energistics 2

### ISSUE THREAD

**Issue by ItzTobias** [ValhelsiaTeam/Valhelsia#213]
I just saw that Applied Energistics 2 updated to 1.15.2.
It would be nice if there was an alternative to Refined Storage.

**Comment by douglasg14b** [comment]
@Khytwel Mind commenting as to the close reason?

**Comment by ValhelsiaTeam** [comment]
We no longer accept suggestions. Besides, GitHub is not meant for that. But thank you for your intervention.
