### ISSUE TITLE
Recipe clash - Sleeping Bags (Comforts) and Wool Slabs (Absent by Design)

### ISSUE THREAD

**Issue by icestorm972** [ValhelsiaTeam/Valhelsia#214]
Both "Sleeping Bags" (Comforts) and "Wool Slabs" (Absent by Design) have the same (16 color versions) recipes: "three wool in a row"

Suggestion:
Replace sleeping bags recipes with a "6 wool slabs" recipe.

`craftingTable.removeByName("comforts:sleeping_bag_black");`
`craftingTable.removeByName("comforts:sleeping_bag_blue");`
`craftingTable.removeByName("comforts:sleeping_bag_brown");`
`craftingTable.removeByName("comforts:sleeping_bag_cyan");`
`craftingTable.removeByName("comforts:sleeping_bag_gray");`
`craftingTable.removeByName("comforts:sleeping_bag_green");`
`craftingTable.removeByName("comforts:sleeping_bag_light_blue");`
`craftingTable.removeByName("comforts:sleeping_bag_light_gray");`
`craftingTable.removeByName("comforts:sleeping_bag_lime");`
`craftingTable.removeByName("comforts:sleeping_bag_magenta");`
`craftingTable.removeByName("comforts:sleeping_bag_orange");`
`craftingTable.removeByName("comforts:sleeping_bag_pink");`
`craftingTable.removeByName("comforts:sleeping_bag_purple");`
`craftingTable.removeByName("comforts:sleeping_bag_red");`
`craftingTable.removeByName("comforts:sleeping_bag_white");`
`craftingTable.removeByName("comforts:sleeping_bag_yellow");`

`var wslb_bk = <item:absentbydesign:slab_wool_black>;`
`var wslb_bl = <item:absentbydesign:slab_wool_blue>;`
`var wslb_bn = <item:absentbydesign:slab_wool_brown>;`
`var wslb_cy = <item:absentbydesign:slab_wool_cyan>;`
`var wslb_gy = <item:absentbydesign:slab_wool_gray>;`
`var wslb_gn = <item:absentbydesign:slab_wool_green>;`
`var wslb_lb = <item:absentbydesign:slab_wool_light_blue>;`
`var wslb_lg = <item:absentbydesign:slab_wool_silver>;`
`var wslb_lm = <item:absentbydesign:slab_wool_lime>;`
`var wslb_mg = <item:absentbydesign:slab_wool_magenta>;`
`var wslb_or = <item:absentbydesign:slab_wool_orange>;`
`var wslb_pk = <item:absentbydesign:slab_wool_pink>;`
`var wslb_pp = <item:absentbydesign:slab_wool_purple>;`
`var wslb_rd = <item:absentbydesign:slab_wool_red>;`
`var wslb_wh = <item:absentbydesign:slab_wool_white>;`
`var wslb_yl = <item:absentbydesign:slab_wool_yellow>;`

`craftingTable.addShaped("sleeping_bag_black", <item:comforts:sleeping_bag_black>, [`
`[wslb_bk,wslb_bk,wslb_bk],`
`[wslb_bk,wslb_bk,wslb_bk]`
`]);`
`craftingTable.addShaped("sleeping_bag_blue", <item:comforts:sleeping_bag_blue>, [`
`[wslb_bl,wslb_bl,wslb_bl],`
`[wslb_bl,wslb_bl,wslb_bl]`
`]);`
`craftingTable.addShaped("sleeping_bag_brown", <item:comforts:sleeping_bag_brown>, [`
`[wslb_bn,wslb_bn,wslb_bn],`
`[wslb_bn,wslb_bn,wslb_bn]`
`]);`
`craftingTable.addShaped("sleeping_bag_cyan", <item:comforts:sleeping_bag_cyan>, [`
`[wslb_cy,wslb_cy,wslb_cy]`
`,[wslb_cy,wslb_cy,wslb_cy]`
`]);`
`craftingTable.addShaped("sleeping_bag_gray", <item:comforts:sleeping_bag_gray>, [`
`[wslb_gy,wslb_gy,wslb_gy]`
`[wslb_gy,wslb_gy,wslb_gy]`
`]);`
`craftingTable.addShaped("sleeping_bag_green", <item:comforts:sleeping_bag_green>, [`
`[wslb_gn,wslb_gn,wslb_gn],`
`[wslb_gn,wslb_gn,wslb_gn]`
`]);`
`craftingTable.addShaped("sleeping_bag_light_blue", <item:comforts:sleeping_bag_light_blue>, [`
`[wslb_lb,wslb_lb,wslb_lb],`
`[wslb_lb,wslb_lb,wslb_lb]`
`]);`
`craftingTable.addShaped("sleeping_bag_light_gray", <item:comforts:sleeping_bag_light_gray>, [`
`[wslb_lg,wslb_lg,wslb_lg],`
`[wslb_lg,wslb_lg,wslb_lg]]);`
`craftingTable.addShaped("sleeping_bag_lime", <item:comforts:sleeping_bag_lime>, [`
`[wslb_lm,wslb_lm,wslb_lm],`
`[wslb_lm,wslb_lm,wslb_lm]`
`]);`
`craftingTable.addShaped("sleeping_bag_magenta", <item:comforts:sleeping_bag_magenta>, [`
`[wslb_mg,wslb_mg,wslb_mg],`
`[wslb_mg,wslb_mg,wslb_mg]`
`]);`
`craftingTable.addShaped("sleeping_bag_orange", <item:comforts:sleeping_bag_orange>, [`
`[wslb_or,wslb_or,wslb_or],`
`[wslb_or,wslb_or,wslb_or]`
`]);`
`craftingTable.addShaped("sleeping_bag_pink", <item:comforts:sleeping_bag_pink>, [`
`[wslb_pk,wslb_pk,wslb_pk],`
`[wslb_pk,wslb_pk,wslb_pk]`
`]);`
`craftingTable.addShaped("sleeping_bag_purple", <item:comforts:sleeping_bag_purple>, [`
`[wslb_pp,wslb_pp,wslb_pp],`
`[wslb_pp,wslb_pp,wslb_pp]]`
`);`
`craftingTable.addShaped("sleeping_bag_red", <item:comforts:sleeping_bag_red>, [`
`[wslb_rd,wslb_rd,wslb_rd],`
`[wslb_rd,wslb_rd,wslb_rd]`
`]);`
`craftingTable.addShaped("sleeping_bag_white", <item:comforts:sleeping_bag_white>, [`
`[wslb_wh,wslb_wh,wslb_wh],`
`[wslb_wh,wslb_wh,wslb_wh]`
`]);`
`craftingTable.addShaped("sleeping_bag_yellow", <item:comforts:sleeping_bag_yellow>, [`
`[wslb_yl,wslb_yl,wslb_yl],`
`[wslb_yl,wslb_yl,wslb_yl]`
`]);`

**Comment by Vaelzan** [comment]
The Polymorph mod adds a button above the crafting output to switch recipes when two conflict. It has compatibility with several different crafting table types and more are being added regularly, so changing recipes isn't required so much anymore for standard crafting.

**Comment by icestorm972** [comment]
Ah, didn't know of polymorph and overlooked the extra "recycle" button in the crafting table showing up...
