### ISSUE TITLE
All sounds except birds gone

### ISSUE THREAD

**Issue by swardhagen** [ValhelsiaTeam/Valhelsia#215]
Hey! I don't know where this issue lies, so maybe it isn't the modpack's fault. The only sounds I hear are birds (several different kinds). All other mobs, ambience, footsteps, tools, breaking is gone. I have checked and my volume is up. It's like every sound file except the birds, was just never installed when I got the pack from Twitch. I had to put in the correct launcher manually because of a bug with starting the game but I don't think that could be causing it. Anyone else having this issue?
Valhelsia 2.2.6 running on Mac OSX 10.12.6.

**Comment by Vaelzan** [comment]
This happens when Twitch hasn't downloaded the contents of the assets folder correctly (or at all). Ideally, switch to GDLauncher or MultiMC. Both have Mac OSX versions.
