### ISSUE TITLE
Engineer's Decor mod update request

### ISSUE THREAD

**Issue by stfwi** [ValhelsiaTeam/Valhelsia#217]
Hi guys, I had a bug report about a client crash in the Factory Dropper GUI when rendering tooltips (Forge mapping change), and implemented a hotfix for Forge versions < 32.0.97. Could you include the fix version `engineersdecor-1.16.1-1.1.1-b6.jar` in the next pack update? Related mod issue thread is https://github.com/stfwi/engineers-decor/issues/114.
Cheers, wile

**Comment by Khytwel** [comment]
Hi, updated in the latest version (3.0.10).
