### ISSUE TITLE
Install attempts from Twitch modpack not working.

### ISSUE THREAD

**Issue by Brosephbraln** [ValhelsiaTeam/Valhelsia#219]
![Valhesia](https://user-images.githubusercontent.com/69206685/89308342-224dda80-d640-11ea-999a-67e62b3b9e6e.PNG)

No java executable found. Cannot execute post-installation tasks for forge.

is what it keeps spitting out in the error message.

**Comment by Vaelzan** [comment]
https://github.com/ValhelsiaTeam/Valhelsia/issues/5
