### ISSUE TITLE
Recipes not working after update from 3.0.9 to 3.0.10

### ISSUE THREAD

**Issue by goaliejordan** [ValhelsiaTeam/Valhelsia#221]
After upgrading our server many recipes are not making the item it specifies in JEI. This seems to be mainly Botania items, but I have also seen it when trying to make a storage drawer item so there are probably others. Is there a work around for this issue?

**Comment by TheSnowyChickens** [comment]
Same same, Botania / Foregoing (Dry Rubber) and some more. :(

V3.0.9 -> 3.0.10

**Comment by Fuggschen** [comment]
same for some refined storage items like the raw advanced processor. makes it literally unplayable

**Comment by therobomega** [comment]
The recipe for Reinforced Blast Brick from Immersive Engineering is also broken.

**Comment by goaliejordan** [comment]
I fixed the issue on the server by removing/disabling the Polymorph mod, thanks to @Vaelzan suggestions.

**Comment by therobomega** [comment]
Disabling the Polymorph mod worked for crafting the Reinforced Blast Brick. Thanks.

**Comment by mchavez1013** [comment]
Having issues with Pam's Harvestcraft Recipes as well

**Comment by rodrigokiller** [comment]
I'm having issues with some recipes too. Sobe blocks like "steel block" or "iron ". When disabling "Polymorth", works good. I tried to downgrade from "polymorph-FORGE-1.16.1-0.12" to version "polymorph-FORGE-1.16.1-0.11", without success, before disabling "Polymorth".

**Comment by mchavez1013** [comment]
Found a fix for the issue with recipes on my end. I am not sure of the long term effects, but i deleted the level.dat file in the world folder. The recipes were working fine again, and the world seems unaffected so far. Will update if i come across any issues regarding this.

**Comment by rodrigokiller** [comment]
> Found a fix for the issue with recipes on my end. I am not sure of the long term effects, but i deleted the level.dat file in the world folder. The recipes were working fine again, and the world seems unaffected so far. Will update if i come across any issues regarding this.

That didn't work for me.

**Comment by Khytwel** [comment]
If you have this problem, please provide us with the logs!

**Comment by rodrigokiller** [comment]
[2020-08-05-2.log](https://github.com/ValhelsiaTeam/Valhelsia/files/5030469/2020-08-05-2.log)
as you wish

**Comment by ValhelsiaTeam** [comment]
https://github.com/TheIllusiveC4/Polymorph/issues/24

**Comment by TheIllusiveC4** [comment]
I've had a hard time reproducing this for testing purposes, but I released Polymorph v0.13 that attempts to fix this issue. Can someone who has this issue currently or has removed/disabled Polymorph try the new version and see if this issue is resolved? Thanks.

**Comment by Khytwel** [comment]
Yeah, apparently the problem's been solved :)
