### ISSUE TITLE
Quark Mod Asks Users for Money

### ISSUE THREAD

**Issue by Xeonen** [ValhelsiaTeam/Valhelsia#222]
Quark mod pops a black screen and asks users for money.

**Comment by aldude999** [comment]
You can remove it if you're comfortable with recompiling a mod by removing the file src/main/java/vazkii/quark/base/client/BLMHandler.java and building it.

I have an already compiled version on my site if you're not comfortable doing that. [https://aldude999.net/index.php/blog/71-quark-r2-2-260-no-blm-nag-screen](url)
Just change the jar name to Quark-r2.2-260.jar and paste it in your mods folder over the old quark. It seems to fix it for me with MultiMC.

**Comment by Xeonen** [comment]
> You can remove it if you're comfortable with recompiling a mod by removing the file src/main/java/vazkii/quark/base/client/BLMHandler.java and building it.
> 
> I have an already compiled version on my site if you're not comfortable doing that. [https://aldude999.net/index.php/blog/71-quark-r2-2-260-no-blm-nag-screen](url)
> Just change the jar name to Quark-r2.2-260.jar and paste it in your mods folder over the old quark. It seems to fix it for me with MultiMC.


Thanks a lot for putting a de-politicized version of the Quart. However, I can not seem to be able to download it from your blog. I generally code in Python and MATLAB so I do not have Eclipse ready with JDK. If you can re-upload it or check the file I will be in your debt.

I miss the times when games were about having fun. These days people can not sleep well if they do not insert nagging about politics into their games.

**Comment by aldude999** [comment]
Copy and paste the URL, for some reason GitHub doesn't like it.
