### ISSUE TITLE
Game crashing at start

### ISSUE THREAD

**Issue by DownloadingRam** [ValhelsiaTeam/Valhelsia#223]
Game fails to boot and doesn't leave an error code. Log below says something about not being able to find the right minecraft instance, but I am unsure

[latest.log](https://github.com/ValhelsiaTeam/Valhelsia/files/5025623/latest.log)

**Comment by Vaelzan** [comment]
Please use our Discord for support and help setting the pack up. There is a FAQ channel there that will help you with that problem. The problem you're having is a Twitch issue and not a pack issue, so it doesn't belong in this issue tracker.
