### ISSUE TITLE
2 bug reports in 1.

### ISSUE THREAD

**Issue by Chibgy** [ValhelsiaTeam/Valhelsia#224]
I have discovered 2 bugs in Valhelsia 3 version 3.0.10 

Bug 1 is where when you are gathering resources it will randomly cut them off into 2 separate stacks of the item and cant be merged together unless you place the block back down and break it again.

Bug 2 is when you plant Cherrywood Saplings from the mod Forbidden & Arcanus the sapling will grow into a vanilla Acacia tree

**Comment by ValhelsiaTeam** [comment]
I can't reproduce the first bug. For the second bug, this one is not present in the last version of the modpack. Reopen an issue if you still have these bugs with the last verison.
