### ISSUE TITLE
Conflicting recipes as a default since 3.0.11

### ISSUE THREAD

**Issue by ncoffman97** [ValhelsiaTeam/Valhelsia#230]
With the removal of Polymorph, the ingame solution to overlapping recipes, there are a lot of items that share the same recipes. By default, there is no way to craft them in game anymore. With conflicting recipes, only one item can be made. This means the user would have to change them in the config by default, which I assume isn't an anticipated goal for every user to default go in and hunt these down. Not sure what the alternative would be with Polymorph gone, just thought I'd bring it up.

**Comment by Vaelzan** [comment]
We're hoping that the removal of Polymorph is only temporary while the bug persists.

If it ends up being a longer-term issue, we will manually create new recipes to resolve conflicts.

**Comment by ValhelsiaTeam** [comment]
https://github.com/ValhelsiaTeam/Valhelsia/issues/221

Subject already listed, I'm closing this issue.
