### ISSUE TITLE
Cannot install the modpack

### ISSUE THREAD

**Issue by Honobe** [ValhelsiaTeam/Valhelsia#234]
I get this message when I try to intall.
"Cannot find file System.Linq.Enumerable+WhereSelectListIterator`2[Curse.Radium.Minecraft.Models.ManifestResource,System.Int32] for addon 231951 in database. Aborting installation."

Not sure what causes it.

**Comment by Honobe** [comment]
I closed and reopened Twitch and now I get "Unable to get Addon: Valhelsia 2 (357858) - File ID: 3028425"

**Comment by Vaelzan** [comment]
CurseForge is currently experiencing issues impacting mod downloads. Please try again later and they will hopefully have resolved the problem. It isn't anything we can deal with and it doesn't just impact Valhelsia.

**Comment by Honobe** [comment]
Thanks!
