### ISSUE TITLE
Mod Suggestion - Ma-Essentials

### ISSUE THREAD

**Issue by HHServers** [ValhelsiaTeam/Valhelsia#237]
Hey, I know that server "essentials" mods are usually up to the server owners - but this mod adds a lot of features/commands and only works if it's installed on both the server and client.

There are a few other popular 1.15 packs with it installed, it would be super useful in conjunction with server-side mods like FTB-Ranks/Teams/Chunks

https://www.curseforge.com/minecraft/mc-mods/maessentials

**Comment by ValhelsiaTeam** [comment]
We no longer accept suggestions. Besides, GitHub is not meant for that.
