### ISSUE TITLE
Can't install Valhelsia 3

### ISSUE THREAD

**Issue by Szaab91** [ValhelsiaTeam/Valhelsia#240]
When i try installing the mod pack i got the following error: Cannot find file System.Linq.Enumerable+WhereSelectListIterator`2[Curse.Radium.Minecraft.Models.ManifestResource,System.Int32] for addon 231951 in database. Aborting installation.

I allready re-installed twitch app and minecraft but it's not working.

**Comment by Szaab91** [comment]
Dear Khytwel, 
Can you please explain why this thread is Dismissed and cloded?

**Comment by landretk** [comment]
It's a Curseforge server issue, not Valhelsia

**Comment by Szaab91** [comment]
Thanks.
