### ISSUE TITLE
Error while download a modpack from twitch

### ISSUE THREAD

**Issue by NuFun2007** [ValhelsiaTeam/Valhelsia#244]
When i try download modpack from twitch then it throws an error:
Cannot find file System.Linq.Enumerable+WhereSelectListIterator`2[Curse.Radium.Minecraft.Models.ManifestResource,System.Int32] for addon 317094 in database. Aborting installation.
Please help.

**Comment by NuFun2007** [comment]
OMG THANKS FOR HELP
BEST DEVELOPERS!!!

**Comment by Tfreak586** [comment]
Just Download the Valhelsia Mod from Curseforge and Install MultiMC its just a fix...

**Comment by Khytwel** [comment]
@NuFun2007 
Unfortunately, you're not able to come to the Discord server or look at the Twitter page and prefer to open a ticket on the GitHub which is ABSOLUTELY not meant for that on our side. 
But of course you're not even able to respect the template to open an issue.
