### ISSUE TITLE
after click play in launcher, it crashes

### ISSUE THREAD

**Issue by jobaq007** [ValhelsiaTeam/Valhelsia#247]
-------------------------------------------------------
**Valhelsia Version:** {v2.2.7}

**Describe the bug:** A clear and concise description of what the bug is.

After pressing play in launcher it crashes, I reinstalled and the issue remains. 

**Logs:** Link(s) to [GitHub Gist](https://gist.github.com/) with full latest.log and/or crash report.

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
2020-08-13 00:09:41,888 main WARN Advanced terminal features are not available in this environment
[32m[00:09:41] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, jobaq007, --version, forge-31.2.33, --gameDir, /Users/josebaquerizo/Twitch/Minecraft/Instances/Valhelsia 2, --assetsDir, /Users/josebaquerizo/Twitch/Minecraft/Install/assets, --assetIndex, 1.15, --uuid, 5def528c8a2a465a913afe73600ef0d9, --accessToken, ❄❄❄❄❄❄❄❄, --userType, legacy, --versionType, release, --width, 2048, --height, 1152, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.33, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601]
[m[32m[00:09:41] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 5.1.2+70+master.2845bb9 starting: java version 1.8.0_261 by Oracle Corporation
[m[32m[00:09:42] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[m[33m[00:09:42] [main/WARN] [ne.mi.fm.lo.FMLConfig/CORE]: Configuration file /Users/josebaquerizo/Twitch/Minecraft/Instances/Valhelsia 2/config/fml.toml is not correct. Correcting
[m[33m[00:09:42] [main/WARN] [ne.mi.fm.lo.FMLConfig/CORE]: Incorrect key [defaultConfigPath] was corrected from null to defaultconfigs
[m[1;31m[00:09:42] [main/FATAL] [ne.mi.fm.lo.FMLCommonLaunchHandler/CORE]: Failed to find Minecraft resource version 1.15.2-20200515.085601 at /Users/josebaquerizo/Twitch/Minecraft/Install/libraries/net/minecraftforge/forge/1.15.2-31.2.33/forge-1.15.2-31.2.33-client.jar
[mException in thread "main" [32m[00:09:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: Missing minecraft resource!
[m[32m[00:09:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.lambda$validatePaths$4(FMLCommonLaunchHandler.java:124)
[m[32m[00:09:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[m[32m[00:09:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
[m[32m[00:09:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.validatePaths(FMLCommonLaunchHandler.java:121)
[m[32m[00:09:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:199)
[m[32m[00:09:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:94)
[m[32m[00:09:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[m[32m[00:09:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[m[32m[00:09:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:981)
[m[32m[00:09:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[m[32m[00:09:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[m[32m[00:09:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[m[32m[00:09:42] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[m

**Comment by Vaelzan** [comment]
When you were posting this, you may have skipped reading this:

> For any help request about a client crash directly after launching or the installation of the modpack/launcher this happens at the Discord server support level (There is a FAQ channel there that will help you with that problem).
