### ISSUE TITLE
Can't launch the mod

### ISSUE THREAD

**Issue by N33K0L4S** [ValhelsiaTeam/Valhelsia#250]
**Valhelsia Version:** {v2.2.7}

Every time I launch the modpack, forge shows that I'm loading the mods, but couple seconds into loading the modpack, the vanilla Minecraft (v 1.15.2) launches. Although it says modded at the bottom screen, it is still the vanilla version of minecraft

![Velhelsia 2 error](https://user-images.githubusercontent.com/69667997/90222661-a2eeb100-de60-11ea-97d5-09cc41c298f0.PNG)

**Comment by ValhelsiaTeam** [comment]
When you were posting this, you may have skipped reading this:

> For any help request about a client crash directly after launching or the installation of the modpack/launcher this happens at the Discord server support level (There is a FAQ channel there that will help you with that problem).
