### ISSUE TITLE
Valhelsia 3 - 3.0.11 - Recipe interference

### ISSUE THREAD

**Issue by TheSpicePhantom** [ValhelsiaTeam/Valhelsia#251]
**Valhelsia Version:** {v3.0.11}

**Describe the bug:**
➥ Trying to craft an item from Immersive Engineering with the same recipe as the Decorative Blocks Iron-Chain.

**Logs:** Link(s) to [GitHub Gist](https://gist.github.com/) with full latest.log and/or crash report.
➥ [Your own kube.js file](https://github.com/ValhelsiaTeam/Valhelsia/blob/1.16/kubejs/data/valhelsia/kubejs/recipes/shaped.js)

**Comment by Vaelzan** [comment]
Which item from Immersive Engineering?

**Comment by Khytwel** [comment]
How can you say there is an interference when the file you are redirecting us to is a file that is not present in version 3.0.11?
