### ISSUE TITLE
Rosewood horizontal Slabs = Vert slabs

### ISSUE THREAD

**Issue by eikotehmouse** [ValhelsiaTeam/Valhelsia#260]
-------------------------------------------------------
**Valhelsia Version:** {v3.0.12}

**Describe the bug:** A clear and concise description of what the bug is.
➥ Rosewood slabs place as vertical slabs. Not sure if this effects other wood types.

**Logs:** Link(s) to [GitHub Gist](https://gist.github.com/) with full latest.log and/or crash report.
➥

**To Reproduce:** Steps to reproduce the bug if necessary.
1. Make Rosewood slabs
2. place slab like you would normally 
3. Vert slabs instead of horizontal 
**Screenshots:** If applicable, add screenshots to help explain your problem.
➥ will add if needing proof....

**Comment by Vaelzan** [comment]
This is intended and part of the of the Double Slabs mod to give vertical slab functionality to every type of slab. You can change the way they place by crouching and/or aiming at different faces of a block.
