### ISSUE TITLE
Twitch does not download Minecraft 1.15.2 on to the mod pack so Minecraft crashes immediately. Please fix because I don't know how to add it.

### ISSUE THREAD

**Issue by PCdaBEST** [ValhelsiaTeam/Valhelsia#267]
Minecraft crashes immediately. Please fix because I don't know how to add it
"Failed to find Minecraft resource version 1.15.2-20200515.085601"

**Comment by Khytwel** [comment]
![image](https://user-images.githubusercontent.com/54046029/90677355-8fc35300-e25d-11ea-9106-2a63a65c30f7.png)
