### ISSUE TITLE
Unable to start up server - Initial start up sequence crashes.

### ISSUE THREAD

**Issue by MatteoVentura** [ValhelsiaTeam/Valhelsia#270]
**Valhelsia Version:** Latest

**Describe the bug:** A clear and concise description of what the bug is.
➥Unable to start up server

**Logs:** Link(s) to [GitHub Gist](https://gist.github.com/) with full latest.log and/or crash report.
➥https://gist.github.com/MatteoVentura/c6b876d85c1b3135871ee1c639fc857f

**To Reproduce:** Steps to reproduce the bug if necessary.
1. Fresh Install 180403 Ubuntu server
2. Install default JRE Java
3. Accept EULA and largen memory restrictions.
4. Run StartServer.sh

**Screenshots:** If applicable, add screenshots to help explain your problem.
➥

**Comment by Vaelzan** [comment]
Modded Minecraft servers require Java 8 (OpenJDK 8 on Linux).
