### ISSUE TITLE
Candles from Extended Lights not craftable

### ISSUE THREAD

**Issue by Redeye123** [ValhelsiaTeam/Valhelsia#28]
When crafted it gives you Bacon not Pigfat .

As reported on my server
![afbeelding](https://user-images.githubusercontent.com/828563/81125244-e53a5500-8f37-11ea-8117-69ca60a7c63f.png)

**Comment by Vaelzan** [comment]
Thank you for the report, Redeye. We will add a new recipe in the next update to work around this.

**Comment by Khytwel** [comment]
Fixed in the version 2.2.0 of Valhelsia 2 :)
