### ISSUE TITLE
Industrial Foregoing:Generators - Game Crash

### ISSUE THREAD

**Issue by olabgaming** [ValhelsiaTeam/Valhelsia#32]
Biofuel Generator crashes game when attempting to access inventory. Getting a divide by 0 java error.

[crash-2020-05-09_12.13.06-client.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4604394/crash-2020-05-09_12.13.06-client.txt)

**Comment by Khytwel** [comment]
https://github.com/NillerMedDild/Enigmatica5/issues/278

**Comment by Khytwel** [comment]
https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/748

**Comment by Vaelzan** [comment]
There are multiple divide by zero issues in the Titanium mod (which is the mod that Industrial Foregoing uses to display their user interface, by the same developer). This can impact multiple machines in Industrial Foregoing, confirmed to at least include the Pitiful Fuel Generator too but potentially more.

**Comment by Vaelzan** [comment]
The mod developer has recently fixed the bug. Assuming the bug fix is on CurseForge before the next pack update (and the mod is otherwise stable), we will include it then.

**Comment by Khytwel** [comment]
Now fixed in the latest version 2.2.2.
