### ISSUE TITLE
Memory issues.

### ISSUE THREAD

**Issue by FrickableBacon** [ValhelsiaTeam/Valhelsia#34]
I have tried on two different computers to play this modpack and every time it gets close to opening up the game it says it has run out of memory. I can play any other modpack except this one for some reason. Is there something I can do? Or is an issue with the pack itself? I deleted every other game on my computer and have 119gb of space free.

**Comment by Redeye123** [comment]
Memory is something different than diskspace if you are using twitch go into the minecraft settings and increase the memory slider to atleast 5 GB .

**Comment by Vaelzan** [comment]
Please use our Discord for support requests (https://discordapp.com/invite/reQZEXu). @Redeye123 was correct in his answer, however - you'll need to increase the memory allocated to Java.
