### ISSUE TITLE
Server download doesn't have the correct server.properties for Biomes O' Plenty

### ISSUE THREAD

**Issue by etsmith43** [ValhelsiaTeam/Valhelsia#35]
server.properties should have level-type=biomesoplenty not default.

**Comment by Vaelzan** [comment]
The server pack download does not contain any server.properties file at all. That file is generated when you run the server. Even if there was one included, we would not necessarily have it set to "biomesoplenty" as "terraforged" is also a popular supported world type that many people prefer, so it is best left up to the server administrator to configure this file.
