### ISSUE TITLE
problem started by crashing mid game

### ISSUE THREAD

**Issue by vangelo** [ValhelsiaTeam/Valhelsia#37]
problem started by crashing mid game, then it crashed soon after loading into the game and now it crashes before i can even join the server

[crash-2020-05-12_15.00.19-server.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4618670/crash-2020-05-12_15.00.19-server.txt)

**Comment by Snowy556** [comment]
I'm by no means an expert, but it appears to be an issue with one of your minecolonies villagers. If nobody else here is able to help, it may help to raise an issue on the minecolonies github page: https://github.com/ldtteam/minecolonies/issues

`-- Entity being ticked --
Details:
	Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.citizen.EntityCitizen)
	Entity ID: 406
	Entity Name: Aiden B. Courtenay
	Entity's Exact location: 267.50, 70.00, -228.50
	Entity's Block location: World: (267,70,-229), Chunk: (at 11,4,11 in 16,-15; contains blocks 256,0,-240 to 271,255,-225), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:536)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)`
