### ISSUE TITLE
FTB Mods?

### ISSUE THREAD

**Issue by DannehSC** [ValhelsiaTeam/Valhelsia#38]
The author of FTB Utilities has updated his mods, which are amazing for servers, to 1.15.2

They simply aren't listed on curseforge, but they are approved "third party mods" or however curse wants to describe them.

FTB Utilities was split into many mods though, like FTB Chunks, arguably the most important.
The updated versions can be found on his website:
https://jenkins.latmod.com/downloadlinks/

**Comment by Khytwel** [comment]
We have neither the authorization and or the possibility to put FTB mods in our modpack. Furthermore, the GitHub is not intended to make mod suggestions.
