### ISSUE TITLE
Can't Host server

### ISSUE THREAD

**Issue by HelpMe10** [ValhelsiaTeam/Valhelsia#39]
I am unable to start the server. At first It would function and I was just unable to join. I got the "Unexpected custom data from client" error message. As I looked around for an answer I tried a few things and happened to screw it up some more. Now when I run the server it will crash immediately after it loads. Here is my most recent crash report, sorry if my problem is a simple fix and waste of time, but I couldn't find my solution anywhere.

[crash-2020-05-13_18.09.25-server.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4625532/crash-2020-05-13_18.09.25-server.txt)

**Comment by Redeye123** [comment]
Minecrafts server is binding on your outgoing IP adress (A ipv6 Adress) and when you connect it gets a ipv4 adress wich screws it up . In minecraft the config file set it to 0.0.0.0 so it doesnt bind on anything and it should let you enter . if not goto https://www.whatsmyip.org/ and use the ip adress shown to connect and hopefully it will be fixed
