### ISSUE TITLE
Apotheosis: Spawners Do Not Drop with Silk Touch

### ISSUE THREAD

**Issue by thebeeskneez** [ValhelsiaTeam/Valhelsia#40]
I have tried to acquire a spawner through Apotheosis's description of dropping with silk touch but it does not seem to work. Attempted on a server and single player world in survival and creative.

**Comment by Scorch-Mechanic** [comment]
You need Silk Touch II to collect spawners. You can get Silk Touch II in all the normal ways you can get other rank II enchantments: By combining two Silk Touch enchantments on an anvil.

**Comment by thebeeskneez** [comment]
Thanks for the info! However, a little bit more reference to that in the modpack would be helpful. I can't find any information stating that there is silktouch II including the mod page. Could Silk Touch be modified to be Silk Touch I so that the assumption could be made that a Silk Touch II exists?
