### ISSUE TITLE
Digital Miner and Builder

### ISSUE THREAD

**Issue by TheSkordeNator** [ValhelsiaTeam/Valhelsia#42]
Both my digital miner (from mekanism) and my builder (from rftools) doesnt start, when i start them they search the area then when they should start breaking blocks they just go to 0. Tested the builder in a a superflat world and it worked fine i also tried making my digital miner only mine vanilla ores and it still didnt work. Is this a common problem or is it something wrong with my world?

**Comment by TheSkordeNator** [comment]
so i tested it out at another place in my world and apparently it works there, i have no idea why this is or how this even is a problem but hey it works

**Comment by Vaelzan** [comment]
Both are almost certainly because of MineColonies - you can grant them permission via the Town Hall, otherwise blocks are prevented from breaking blocks inside the colony.
