### ISSUE TITLE
Minecolonies : new players not being able to place supplycamps

### ISSUE THREAD

**Issue by Redeye123** [ValhelsiaTeam/Valhelsia#43]
Last update (2.2.0a) new players are not able to place down new supplycamps . they tell me they see the schemetic then when they place it down its not being build and the item is gone .

This makes them not bieng able to get the townhall 

Our workarround is to just give them one trough commands .

**Comment by Khytwel** [comment]
Please report this bug directly to the developers of MineColonies.
