### ISSUE TITLE
Lightest Lamps: Lighting Breaking upon server restart in 2.2.0

### ISSUE THREAD

**Issue by mleslie0401** [ValhelsiaTeam/Valhelsia#45]
Upon server restart, it seems like the lamp light/penetration all breaks and every lamp needs to be reset or broken and replaced each time.  This has been tested specifically with the Gamma Lamp since its the earliest lamp with penetration.

When the issue presented itself - 2.2.0 update.

**Comment by Khytwel** [comment]
Please report this bug directly to the developer of Lightest Lamps.

https://github.com/DcZipPL/lightestlampsmod/issues
