### ISSUE TITLE
Inventory mangment button overlay crafing grind in crafting station

### ISSUE THREAD

**Issue by xanderio** [ValhelsiaTeam/Valhelsia#46]
![grafik](https://user-images.githubusercontent.com/6298052/82076834-ae560300-96de-11ea-9ff2-833f72a73e30.png)

**Comment by Vaelzan** [comment]
This has been fixed for the next update. :)

**Comment by Khytwel** [comment]
Now fixed in the latest version 2.2.2. Thanks for your report.
