### ISSUE TITLE
Can you please add chunk loader?! 

### ISSUE THREAD

**Issue by NancVn** [ValhelsiaTeam/Valhelsia#47]
I cant find any chunk loader

**Comment by MelanX** [comment]
Use teleporters with anchor upgrades.. or were they disabled? idk
Or just add a mod for yourself like me :)

**Comment by Vaelzan** [comment]
Anchor Upgrades were disabled as they were preventing servers from starting up after certain crashes. It was getting really hard to support. We haven't found a good chunk loader yet that actually works well on servers.

**Comment by MelanX** [comment]
I use FTB Chunks and it works fine. And just because it’s not on CurseForge, it doesn’t mean you’re not allowed to use it in pack.
I made it as a suggestion ~2 weeks ago but it was deleted after 2 minutes and I don’t know why. But yeah.. adding FTB Chunks would help.
