### ISSUE TITLE
it used to work and now it doesnt

### ISSUE THREAD

**Issue by vangelo** [ValhelsiaTeam/Valhelsia#49]
it used to work fine but now it like starts up the server im running loads everything then i cant even use cmd commands on it like its not taking commands and when i try to go onto my minecraft and hook up to the server it loads for a bit then just says timed out. this is the crash log that i think goes with it

[crash-2020-05-16_18.37.08-server.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4639525/crash-2020-05-16_18.37.08-server.txt)

**Comment by Redeye123** [comment]
Looks like your not running latest version . Looking at your forge version 31.1.74 while latest is 31.1.87 .

**Comment by vangelo** [comment]
yes but my server and my mod pack are both running that version of forge?
i tried to update the modpack but it deleted ALOT of blocks in game so i rolled it back to the last version

**Comment by Vaelzan** [comment]
We handle crash reports on the Discord server's support channel. Please check there. See here: https://github.com/ValhelsiaTeam/Valhelsia/issues/5

**Comment by Vaelzan** [comment]
Having said that, with that many errors in different mods I suspect something weird happened when you rolled back. Please try reinstalling from scratch. You can keep the world / save (make a copy of it). Ideally though, you really should update. Don't let the removed blocks worry you. The mods were removed for a good reason (crashes + bugs).
