### ISSUE TITLE
can't craft Smooth sandstone and Smooth Red Sandstone

### ISSUE THREAD

**Issue by cedpat4** [ValhelsiaTeam/Valhelsia#50]
you should be able to smelt sandstone to get smooth sandstone. but it dosnt work. i think Embelishcraft removed the recipe.

**Comment by Vaelzan** [comment]
We're aiming to have this fixed for the next release of the mod pack. Thank you for the report.

**Comment by Khytwel** [comment]
Fixed, thanks for your report!
