### ISSUE TITLE
[Minecolonies] SupplyShip and SupplyCamp not working

### ISSUE THREAD

**Issue by sky0matic** [ValhelsiaTeam/Valhelsia#51]
**Issue :** 
The SupplyShip/SupplyCamp from Minecolonies won't build entirely which result in missing key feature to start on the mod like no Town Hall item given.

**Expected:**

The SupplyShip/SupplyCamp to build entirely and has the Town Hall item (not craftable) and the Building Tool.

Modpack version : 2.2.0a

**Comment by Vaelzan** [comment]
This may be related to https://github.com/ValhelsiaTeam/Valhelsia/issues/43 but I am unsure from the description. MineColonies updates multiple times per day (which we can't keep up with), so there's a good chance it will be fixed by the next pack update, but I haven't been following this bug. It may be best to ask on their own Discord server.

**Comment by lord-nytmare** [comment]
We currently have the same bug as #43, but our Pirate raids ships are spawning broken, which might link to this.
https://i.imgur.com/S80Dvvt.jpg
I had to break the spawners before taking the pic, but it didnt stop pirates from spawning.

**Comment by JakeMoe** [comment]
FWIW, I had trouble getting the ship to place (was putting it in a large-ish lake that apparently just wasn't large enough), but when I placed the SupplyCamp, I was similarly distressed to find I couldn't find the town hall.  After looking around it for 5 minutes or so, I realized that most of the racks that held the starter items weren't rendering, but I found Minecraft was highlighting the block when I was looking at it, and I could right-click it then and get Town Hall, building tool, starter foods, etc.  The next time I relogged, the racks were visible.

**Comment by sky0matic** [comment]
@JakeMoe Weird .. When that happened for me, none of the blocks were there for me, even after a game reload.

**Comment by JakeMoe** [comment]
Oh, when you said it wouldn't build entirely, thought you might have meant like I saw.  Sorry, nothing to add to your problem then. :-(

**Comment by Vaelzan** [comment]
I think this may be fixed in 2.2.2, please check and let me know.
