### ISSUE TITLE
Ore generation

### ISSUE THREAD

**Issue by Habeeb-M** [ValhelsiaTeam/Valhelsia#52]
After playing this pack for close to 10 hours, I have realised the ore generation in this pack isn't done terribly well. The majority of the underground is marble, or limestone, or other modded stones.

The first problem with this is that vanilla stone is very hard to come by; the only cobble I managed to get was from a Quark cobweb cave. The only other way I saw was to maybe find some structures above ground, but this seems like its horribly overlooked. Most recipes have not been altered to take modded stone types.

The other problem is my main problem; ores seem to have not been configured at all. No ores spawn in marble or limestone, which means when I mine, I get barely any ores. A turtle, on a `tunnel 100` command, gathers less than 10 of any ores in total, and maybe uncovers less than 20, which I find insane. I have not found a single diamond ore, in a 15*100 area at level 12 with turtles; the only diamonds I have found are from a quark big cave, and from a couple above ground structures.

I cannot tell if this is a stylistic choice, but it is making the game unreasonably hard. Any responses are appreciated.

**Comment by Vaelzan** [comment]
What world generation are you using? Every world I've created is flooded with vanilla stone and ores, with only smaller patches of modded stone around. If you're seeing something different, it certainly isn't the norm for the pack.

**Comment by Habeeb-M** [comment]
I may be on an older version, but I'm using the TerraForged world gen. I was notified that TerraForge may be the culprit, though. I realise I may have sounded a bit aggressive in the original post, so I apologise.

For some more examples, after making a 100*10 area at level 12, I only found [these items](https://cdn.discordapp.com/attachments/687707494147293187/711658923408621578/unknown.png), and finally after mining a 100*50 area, I found my first diamond vein(consisting of 3 ores).

**Comment by Vaelzan** [comment]
I'll have to take a look at the Terraforged issue tracker. It worked well enough in previous versions but they may have introduced a recent bug - as with many 1.15.2 mods, it's in very active development and changes a lot.

**Comment by Vaelzan** [comment]
Yep, update the pack. The version of TerraForged in the latest pack release has at least some fixes, notably that ores now spawn in place of modded stones rather than only where vanilla stone was.

**Comment by Vaelzan** [comment]
https://github.com/TerraForged/TerraForged/issues/167

**Comment by Vaelzan** [comment]
For the other issue, of not finding vanilla stone at all: I believe, but can't test at the moment, that it is configurable when you first generate the world since TerraForged changes the distribution of stone quite substantially. If you don't want to restart the world (understandably), then you can look elsewhere in the world, as different stone appears in different regions.

**Comment by Habeeb-M** [comment]
Alright, thank you. I appreciate the time and am enjoying the pack!
