### ISSUE TITLE
Iron bridge craften is not possible (Mod Macaw's Bridges) Valhelsia 2.0.2a

### ISSUE THREAD

**Issue by egemasta** [ValhelsiaTeam/Valhelsia#57]
Hello

Unfortunately I cannot make an Iron Plate from the Mod Macaw's Bridges (mcw-bridges-1.0.4fix-mc1.15.2.jar). If I put 3 Iron Ingot into the crafting interface, I only get the Iron Beam of EmbellishCraft (embellishcraft-1.15.2-2.2.0.0.jar). Unfortunately you can't craft a whole iron bridge this way.

Version: 2.2.0a

Minecraft version: 1.15.2

(modded) forge-31.1.87

Greetings
Egemasta

**Comment by Khytwel** [comment]
Fixed, thanks for your report!

**Comment by egemasta** [comment]
> Fixed, thanks for your report!

Thanks for the Fix.
