### ISSUE TITLE
mods won't load 

### ISSUE THREAD

**Issue by lavical** [ValhelsiaTeam/Valhelsia#59]
I made a mods folder, extracted the zip into the folder, loaded forge, and I only had two mods loaded.

**Comment by Vaelzan** [comment]
You're not installing the pack correctly (or in fact, at all - that zip doesn't contain the mods). Please use Discord for support requests and look at the #faq channel there. https://discordapp.com/invite/reQZEXu

https://github.com/ValhelsiaTeam/Valhelsia/issues/5
