### ISSUE TITLE
Lexica Botania not updating

### ISSUE THREAD

**Issue by AlexGPTB** [ValhelsiaTeam/Valhelsia#60]
My Lexica Botania was working perfectly until a couple of days ago, when all the information got reset. Now I can't unlock any new entries even if I do the early game ones again.

**Comment by Vaelzan** [comment]
I'm not familiar enough with the way Bosnia stores the Lexica Botania unlocks to know what may have caused this. Have you tried this to the Botania GitHub issue tracker too?

**Comment by AlexGPTB** [comment]
Figured out the fix, had to remove the botania advancements and redo them to fix the book unlocks.
