### ISSUE TITLE
Increased drop rate of items from some mods (Forbidden and Arcanus, MineColonies)

### ISSUE THREAD

**Issue by ieolivares9742** [ValhelsiaTeam/Valhelsia#62]
I'm getting an absurd amount of F&A drops from mobs. So far I've tested on squids and endermen where i get over 5 stacks of respective drops from a single mob (tentacles and pearl fragments). Vanilla and other mod drops seem to work like normal. 

I first thought it was my silent's gear sword that has luck IV on it but I killed an enderman with a vanilla sword and got a generous amount of fragments as well. Paxel gave normal drops and haven't tried other weapons. 

But hey if this is intended then I am grateful because I need pearls but my conscious won't allow me to accept bugged drops :b

**Comment by ieolivares9742** [comment]
Forgot to mention: the drops weren't happening in version 2.2.0a but started to once we updated the pack to 2.2.1a, in case that helps.

**Comment by silentstormpt** [comment]
Still happening on 2.2.1a to minecolonies mobs, all raiders droping crazy amounts of drops

**Comment by MacScarfe** [comment]
I'm also experiencing this issue, however as well as Endermen, i also get large drops form Pirates, every pirate so far drops at least 1 tome and at least 8 cutlass.

**Comment by Khytwel** [comment]
I don't have that problem on my side, which sword do you use?

**Comment by silentstormpt** [comment]
Refined Obsidian Sword with Looting II

**Comment by Vaelzan** [comment]
If pirates are also having issues, then it isn't just Forbidden and Arcanus. It does make it a bit harder to track down. Has anybody noticed if vanilla drops have this issue at all?

**Comment by silentstormpt** [comment]
In case of the Enderman, only the Ender pearl shards have ridiculous drop rates, Ender pearls rate looked normal while on MineColonies all items on NPCs have crazy drops

**Comment by MacScarfe** [comment]
Using a silent gear based sword (bismuth steel/brass mix) with no enchantments.
As above only ender pearl shards and pirate drops (not had a barbarian attack in a long time),
I kill loads of skellies, zombies (+baby varieties) and spiders and all drops are normal for those mobs.

**Comment by rabalais** [comment]
Updated server to 2.2.1a and now endermen drop ridiculous amounts of ender pearl fragments. Haven't tested other mobs. (Killed using silent gear based katana w/ enchantments that don't affect drop rate)

**Comment by Saporous** [comment]
I've ran into this unexpected behavior myself after creating a looting/luck machete. It seems like it's an interaction between only Forbidden & Arcanus specific mob drops and Silent's Gear tools, so I've created an issue on both mod's issue trackers, here's the links.
https://github.com/SilentChaos512/Silent-Gear/issues/129
https://github.com/stal111/Forbidden-Arcanus/issues/64

**Comment by Vaelzan** [comment]
If anybody encounters this, please give me details of what weapon you were using - was it from Silent Gear? If so, what materials and enchants? Did it happen with any vanilla weapons? Did it ever happen with unenchanted gear?

**Comment by Vaelzan** [comment]
I just confirmed that it doesn't just happen with Silent Gear. Dungeon Chests also have increased quantities of Forbidden and Arcanus loot in them.

**Comment by Vaelzan** [comment]
Scrap that last comment. Silent Gear added a Lucky trait that can impact dungeon chest generation. Seems like something weird might be going on with the luck attribute somehow?

**Comment by silentstormpt** [comment]
Quite possible, a friend of mine join in and he also had the same bug happen without any gear and an vanilla sword meaning this happens regardless of what ur using

**Comment by Vaelzan** [comment]
This has been fixed in the latest version of Silent Gear, and will be included in the next pack update.

**Comment by Khytwel** [comment]
Now fixed in the latest version 2.2.2. Thanks for your report.
