### ISSUE TITLE
Unable to find Diamonds

### ISSUE THREAD

**Issue by Dogylover200** [ValhelsiaTeam/Valhelsia#63]
I've been digging at y=11 for a while now, about 5 hours and I have been unable to find a single diamond, I've also gone into the ravines and caves and all manner of caving and still unable to find diamonds, possibility that diamonds just aren't spawning in Biome's of Plenty worlds?

**Comment by Vaelzan** [comment]
I think what's happening is that there are fewer of them because they can't replace modded stone normally, only regular stone. In the next update some of the modded stone types will be spread out a bit (less common to find a pocket), so diamonds should be easier to come across. They definitely do appear though, just not as frequently as vanilla Minecraft.

**Comment by OfficialStamper** [comment]
Can you conform when the worldgen will be adjusted please?

I started playing Valhelsia-2-2.2.1a today in SP world (to try out before putting up on server), and like Dogy above, 5 hours and no diamonds, plus very few Ores full stop.  Yet I have stone of every Color, Size, Shape and Creed beyond belief.  imo, current Worldgen, is unplayable.

(FYI. World created using TerraForged with BOP.)

**Comment by Vaelzan** [comment]
TerraForged is a different case entirely. That isn't something that we can't fix other than including TerraForged updates as they update the mod. It specifically replaces far more stone than normal with modded stone and not all of it gets replaced with ores. I believe there is an issue on their own issue tracker regarding this problem.

For other generation such as Biomes O Plenty worlds, the updated configs are ready to go whenever the next pack version is released (this is up to Khytwel).

**Comment by Khytwel** [comment]
Now fixed in the latest version 2.2.2. Thanks for your report.
