### ISSUE TITLE
Refined Storage Crashes Server Due to Crafting Monitor Bug

### ISSUE THREAD

**Issue by backlands** [ValhelsiaTeam/Valhelsia#64]
There was an issue in the current version of Refined Storage included in this modpack. The issue has now been patched in Refined Storage and the issue causing the crash appears to be corrected. You can see the new version in their changelog [here](https://github.com/refinedmods/refinedstorage/blob/mc1.15/CHANGELOG.md).

For some [additional detail](https://github.com/refinedmods/refinedstorage/issues/2508), the crash was cause in Refined Storage when a complex autocrafting task either completed itself or was cancelled while a user was viewing information in the Crafting Manager. Just wanted to drop a message in the hopes that the new Refined Storage version gets into the next release. This bug causes the entire server to crash when it is triggered (fairly easily since it occurs when a user utilizes the Refined Storage crafting manager).

**Comment by Vaelzan** [comment]
Thanks for the report. We've been following this bug, and in fact the RS code was patched on GitHub before the last pack update but it hadn't made it onto CurseForge yet so we couldn't include it at the time. It will absolutely be in the next update unless there are any other unforeseen issues.

**Comment by Vaelzan** [comment]
Refined Storage has been updated in the latest release, 2.2.2.
