### ISSUE TITLE
Getting this error message. 

### ISSUE THREAD

**Issue by starwind3438** [ValhelsiaTeam/Valhelsia#65]
https://gyazo.com/15f0582180374a45709cc3accad77815

https://paste.ubuntu.com/p/K5GKrmVh2n/

**Comment by MoarDm** [comment]
You are using Forge v31.2.5
try to use 31.2.0
Works for me

**Comment by Dheumanizer** [comment]
Same error for me using Forge v31.2.5. After downgrade to 31.2.0 forge version (thx MoarDm) it's work
