### ISSUE TITLE
broke tools red line across entire screen left of tool durability line after update

### ISSUE THREAD

**Issue by jermacalocas** [ValhelsiaTeam/Valhelsia#66]
updated from 2.2.0 to 2.2.1 

also 2 of my tools went from full durabity to broke

**Comment by Vaelzan** [comment]
This is an issue with the Silent Gear update. There's a command to recalculate the stats of tools after you update - `/sgear_recalculate @p` that should fix this for all of your items.

**Comment by jermacalocas** [comment]
thank you, ill try that. do you know if this fixes the red line and the durability or just the red line?

**Comment by Vaelzan** [comment]
You may need to repair the tool after running the command but it should then function as normal. For more information, check the Silent Gear GitHub issues page - a number of weird issues have popped up sure to the changes.

**Comment by Vaelzan** [comment]
Did running that command fix the issue for you?

**Comment by jermacalocas** [comment]
i am now updating it today, doing the 2.2.1 then 2.2.2 and checking to see if this works. ill be back to this in a little bit to update you

**Comment by jermacalocas** [comment]
update: im now on 2.2.2 and ran the /sgear_recalculate @p command and that fixed it. thank you! this whole modpack is amazing
