### ISSUE TITLE
Double half slab disappeares when mined, new block placed there crashes the game

### ISSUE THREAD

**Issue by DanielLakatos** [ValhelsiaTeam/Valhelsia#69]
**Repro:** 

- Put two half slabs on each other (I did with cobblestone)
- Mine them with a pick (I had a Silent Gear Reinforced iron pick)
- It will disappear at the last moment when it should be mined (no resources came back)
- Place a block where it was/is
- Crash

**Crash Report:**
[crash-2020-06-06_15.01.10-client.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4740062/crash-2020-06-06_15.01.10-client.txt)

**Comment by Vaelzan** [comment]
There was an update to double slabs a couple of hours ago that may fix that. For now, please update the mod to that version and let us know if it resolves the problem. The fixed version will be included in the next pack release.

**Comment by Khytwel** [comment]
Fixed in the latest version 2.2.2a.
