### ISSUE TITLE
Optifine models play up

### ISSUE THREAD

**Issue by steamzeus93** [ValhelsiaTeam/Valhelsia#71]
When running Optifine the 3d Models for Minecolonies are invisable in hand and are a pink and black debug square after being placed. this isn't for all models just about 5 or 6 of them.

**Comment by Vaelzan** [comment]
This is because OptiFine doesn't support rendering certain Forge 3D models. The same thing happens with some Mekanism things (jetpack, free runners, etc.). It isn't something we can fix on our end, OptiFine isn't finished yet for 1.15.2, and it also isn't part of the pack.
