### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by DimmerSteam** [ValhelsiaTeam/Valhelsia#72]
The game crashes every time I try to launch it.

**Comment by Vaelzan** [comment]
Please read the pinned README (https://github.com/ValhelsiaTeam/Valhelsia/issues/5) before posting issues. This is not the place for support regarding crashes, and even if it was there isn't enough information provided.

Instead, read the #faq channel on Discord and if that doesn't solve the problem, ask in #support there. The Discord can be found here: https://discordapp.com/invite/reQZEXu
