### ISSUE TITLE
Game error

### ISSUE THREAD

**Issue by mason5mith** [ValhelsiaTeam/Valhelsia#73]
whenever i start valhelsia 2 up, it'll load for about a minute then give me an error; 
GLFW error 65539: invalid key 2.
i've reinstalled stuff, updated drivers, tried different launchers, nothing.
when i reinstall the pack it works once then if i load it up another time the same error appears. I've asked on the discord, but no one seems to know how to fix it.
![Annotation 2020-06-08 112435](https://user-images.githubusercontent.com/8309780/84061477-e129a900-a9b5-11ea-978d-3fda984da325.png)

**Comment by madhatr** [comment]
Do you have a key binding [gaming mouse](https://www.minecraftforum.net/forums/support/java-edition-support/3020721-glfw-error-65539-minecraft-invalid-key-3)?

Another link [here](https://github.com/AllTheMods/ATM-5/issues/32) references gaming mouse with extra buttons.  

Seems if you try to bind stuff from mekanism(maybe) to the extra mouse buttons it causes this error.

**Comment by Vaelzan** [comment]
I'm pretty sure this was resolved on Discord earlier. @madhatr gave the right link for the fix (the linked GitHub issue). If anybody else has the same problem, follow that link.
