### ISSUE TITLE
mekanism blocks lagging

### ISSUE THREAD

**Issue by Ritritz** [ValhelsiaTeam/Valhelsia#81]
Im using mekanism blocks and theyre lagging in the actual ui itself
im getting now character lag or anything its just taking 3 times as long to use anything mekanism

**Comment by Atzenheer** [comment]
I can confirm this for Valhelsia 2.2.0a. First I thought this could be a conflict with MineColonies as the Mekanism machines were located within the borders of a colony. But even outside of the colony borders the machines are lagging. This is a behavior I have never seen before for Mekanism machines.

**Comment by Khytwel** [comment]
No more development for Mekanism in 1.15. Maybe fixed in the latest version of the mod maybe not.
