### ISSUE TITLE
Breaking xnet cable/connectors

### ISSUE THREAD

**Issue by Dayo16** [ValhelsiaTeam/Valhelsia#83]
Breaking xnet cable connector crashes the game. Xnet team has figured out a solution I just want to bring this to light so that you know to update Xnet when they release it. Reference: https://github.com/McJtyMods/XNet/issues/421 and https://github.com/McJtyMods/XNet/issues/419

**Comment by Vaelzan** [comment]
Thanks for the report. We'll include it in the next pack update.
