### ISSUE TITLE
Totem of Undying issue

### ISSUE THREAD

**Issue by jermacalocas** [ValhelsiaTeam/Valhelsia#84]
totem of undying in my charms slot, died and stuck in death pose after being brought back to life. cant WASD move and some of the hotbar items are stretching weird. backpacks cannot be opened, accessories inventory cant be opened. Saved game and reloaded and it works fine.

**Comment by macrosblackd** [comment]
Happened to me as well.

**Comment by Vaelzan** [comment]
I think this may be fixed now, please test with 2.2.3. I suspect it was a bad interaction with the hardcore revival mod which has been removed.
