### ISSUE TITLE
client crash the end shift click slab

### ISSUE THREAD

**Issue by Coji4000** [ValhelsiaTeam/Valhelsia#85]
on the spawn platform in the end if you hold shift to not fall off the platform and right click with a cobblestone slab to place it in the lower half of the block space it causes a client crash. Seems repeatable. appears to be some issue with placing the slab vertically there.

Valhelsia 2 ver. 2.2.2a

[crash-2020-06-16_17.51.42-client.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4789317/crash-2020-06-16_17.51.42-client.txt)

**Comment by Vaelzan** [comment]
Please see if updating the Double Slabs mod resolves this.

If it does not, please report it to the Double Slabs developer here: https://github.com/CJMinecraft01/DoubleSlabs/issues

**Comment by Coji4000** [comment]
The issue is resolved with Double Slabs ver.2.5.1 thank you!
