### ISSUE TITLE
mining turtle/stella arcanum server crash

### ISSUE THREAD

**Issue by Coji4000** [ValhelsiaTeam/Valhelsia#86]
If a mining turtle encounters a stella arcanum ore while using the tunnel command the server crashes when the turtle mines the ore ONLY IF the ore explosion causes a second stella arcanum ore explosion (chain reaction). repeatable. in creative place 2 arcanum blocks on top one another then send the turtle tunneling towards the arcanum.

Valhelsia 2 ver.2.2.2a

[crash-2020-06-16_18.18.43-server.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4789373/crash-2020-06-16_18.18.43-server.txt)

**Comment by Vaelzan** [comment]
We've updated CC: Tweaked in the latest Valhelsia 2 update. Please let me know if this resolved the issue. If not, please report it to the CC: Tweaked issue tracker.

**Comment by Coji4000** [comment]
just pulled the latest update and im no longer able to recreate. it's looking good. thanks!

**Comment by MoarDm** [comment]
original issue
https://github.com/SquidDev-CC/CC-Tweaked/issues/462
