### ISSUE TITLE
Shaders makes my screen xray when mining.

### ISSUE THREAD

**Issue by CausticKiller** [ValhelsiaTeam/Valhelsia#87]
I have OptiFine  version 1.15.2 HD U G1 pre26 installed with Sildur's Vibrant shaders v1.27 High. I tried two other shaders and both gave me the same issue. It happens only when I mine with a tool.
![2020-06-17_18 13 43](https://user-images.githubusercontent.com/67070713/84934125-e5844f00-b0a4-11ea-8f60-1744c07f8e06.png)

**Comment by Vaelzan** [comment]
This is an issue with recent versions of OptiFine. If you can find one, try using a slightly older preview (21 or earlier).

**Comment by CausticKiller** [comment]
> 
> 
> This is an issue with recent versions of OptiFine. If you can find one, try using a slightly older preview (21 or earlier).

Thanks!
