### ISSUE TITLE
Unable to connect to same version server on fresh install.

### ISSUE THREAD

**Issue by Wertww** [ValhelsiaTeam/Valhelsia#89]
Hello world,

I have been attempting to join my friends on a private server by downloading the latest of this pack (Ver 2.2.2a) via the Twitch client. My friend says he has the latest server pack and essentially all of this is trying to use it straight out of the box. However I can not connect and get a warning that says the following: "Incompatible FML modded server | Server mod list is not compatible". When connecting I just get a generic, "Could not connect to server, Disconnected."

I have tried to connect to other servers after experiencing this issue and I keep running into the same thing. I have no idea if I did anything wrong or if the Twitch downloader is messing up. If anyone can point me in the right direction I would be appreciative.

**Comment by Vaelzan** [comment]
The Incompatible FML modded server is normal, it mentions it in the server pack readme. Please use our Discord for support though, this is not the appropriate place (see: https://github.com/ValhelsiaTeam/Valhelsia/issues/5)
