### ISSUE TITLE
Unnable to install the server file to Ubuntu

### ISSUE THREAD

**Issue by CausticKiller** [ValhelsiaTeam/Valhelsia#90]
[crash-2020-06-18_00.53.35-server.txt](https://github.com/ValhelsiaTeam/Valhelsia/files/4800658/crash-2020-06-18_00.53.35-server.txt)
I have no clue what to do. It works when I remove all the mods from the mods folder. The same server files work on Windows 10.

**Comment by Vaelzan** [comment]
You've added at least one mod there, Falling Tree, and you didn't include the 1.15.2 version, you added the 1.14.4 version instead.

**Comment by Vaelzan** [comment]
You also have the wrong version of Java. The pack requires Java 8, you're running Java 11. Please also use Discord for support in the future.
