### ISSUE TITLE
Adjusting Resolution Has No Effect

### ISSUE THREAD

**Issue by Cronje99** [ValhelsiaTeam/Valhelsia#92]
Going into Video Settings and moving the slider bar for the resolution does not have any effect. I wanted to adjust it to my monitor's resolution, since "Fullscreen Resolution: Current" is not, in fact, full screen (there's a gap at the bottom through which you can see other windows), but no matter where I moved the slider, nothing changed.

I expected there would be some sort of prompt telling you the game needed to restart, but nothing appeared. Manually reloading also had no effect.

**Comment by Vaelzan** [comment]
Adjusting the fullscreen resolution won't have a visible effect until you press the fullscreen toggle button, F11 by default, just like in regular Minecraft.

**Comment by Cronje99** [comment]
Given the slider's values, I wouldn't have assumed that the value chosen applies ONLY when the screen is in fullscreen mode. Perhaps this should be changed. If the first notch on the slider is "Fullscreen Resolution" and the next notch over is "1920x680@60 (24bit)," I should be able to safely assume that it sets the game resolution in general, not just when it is in fullscreen mode.

**Comment by Vaelzan** [comment]
Please be aware that this is the exact same slider as regular Minecraft 1.15.2. The mod pack changes nothing here at all. You're welcome to ask Mojang to change it if you would like, but we don't change it in the slightest.

**Comment by Cronje99** [comment]
I was unaware of this. I've been playing 1.12.2 for too long, it seems. Closing issue.
