### ISSUE TITLE
Suggestion: Add Taffy

### ISSUE THREAD

**Issue by cinnamennen** [ValhelsiaTeam/Valhelsia#93]
Mod: https://www.curseforge.com/minecraft/mc-mods/taffydaf

It's a serverside mod that just adds some nice info to the server description

**Comment by Vaelzan** [comment]
We prefer to leave server-only mods up to individual server administrators, since they can then make decisions like this for themselves. In the future we may compile a list of mods that they might want to consider adding though, and this looks like a good candidate for that.
