### ISSUE TITLE
Can't rejoin dedicated server after disconnecting/getting kicked/crashing after playing several hours

### ISSUE THREAD

**Issue by TitanGuard** [ValhelsiaTeam/Valhelsia#95]
Sorry if this doesn't go here, it seems like the appropriate place though.
Modpack: Valhelsia 2 version 2.2.2a
Running through the Multi Minecraft Launcher

I'm not sure what's going on with this, don't know if there is a log file anywhere to help so i can't get one at this moment, but this is directly from the server's console.

 [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize biomesoplenty.common.command.BiomeArgument@16b4d976 (class biomesoplenty.common.command.BiomeArgument) - will not be sent to client!
[m[1;31m[22:59:10] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@73433f2b (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
[m[1;31m[22:59:10] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIdArgument@797ac4cb (class net.minecraftforge.server.command.ModIdArgument) - will not be sent to client!
[m[1;31m[22:59:10] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@c098b10 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
[m[1;31m[22:59:10] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@58aa729b (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
[m[1;31m[22:59:10] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@4263deef (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!
[m[1;31m[22:59:10] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize com.ldtteam.structurize.commands.arguments.MultipleStringArgument@1e29dec3 (class com.ldtteam.structurize.commands.arguments.MultipleStringArgument) - will not be sent to client!

it gives these lines each and every time i try to join back on the server and it just kicks me with "Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host" tagline.

**Comment by Balthizar01** [comment]
You'll find a logs folder in your files that has a latest.log. You can come into the Discord and we can try to help you better there.

-Kanadet

**Comment by Vaelzan** [comment]
As Kanadet mentioned, please get help for this on Discord. :)
