### ISSUE TITLE
Silentgear requires forge 31.2.5 or above error

### ISSUE THREAD

**Issue by 03453404558** [ValhelsiaTeam/Valhelsia#97]
After updating my server to the latest version of the modpack i have an error message whenever trying to start the server saying-
21.06 10:02:43 [Server] INFO net.minecraftforge.fml.ModLoadingException: Mod silentgear requires forge 31.2.5 or above
21.06 10:02:43 [Server] INFO Currently, forge is 31.2.0

**Comment by Vaelzan** [comment]
You didn't update Forge when you updated the server. The version that comes with the server pack is newer than that.

**Comment by 03453404558** [comment]
I completely swapped over all of the server files including the new forge versions.

**Comment by 03453404558** [comment]
The version that is in my server files is forge 31.2.21

**Comment by Vaelzan** [comment]
Did you paste the new ServerStart script too?

**Comment by 03453404558** [comment]
I think that i have sorting out that issue however i now have an issue that the server that i was on cant load as it keeps getting stuck saying- 21.06 13:14:31 [Server] Server thread/WARN [ne.mi.fm.FMLWorldPersistenceHook/WP]: This world was saved with mod titanium version 2.4.1 and it is now at version 2.4.2, things may not work well

It goes past every other mod however when it gets to titanium it stops loading. I know i can just make a new world to fix this, but ideally i can stay on the same world, any idea on how to get past this issue?

**Comment by Vaelzan** [comment]
It usually asks you somewhere there to type "/fml confirm" to confirm changes.

**Comment by 03453404558** [comment]
I don't seem to get that prompt, I tried typing it anyways and unfortunately it doesn't seem to have done anything.

**Comment by 03453404558** [comment]
I did a restart and run the command again whilst it was stuck and it seems to fixed the issue
